### ISSUE TITLE
Turf/circle throws errors when passing optional arguments

### ISSUE THREAD

**Issue by drewbo** [Turfjs/turf#1023]
Version: `5.0.0`

The following code works fine:
```js
var circle = require('@turf/circle')
circle([0, 0], 1)
// { type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [ [Object] ] } }
```

However when passing other arguments, it looks like it might be expecting an options object rather than individual arguments. For example:

```js
var circle = require('@turf/circle')
circle([0, 0], 1, 8)
// Error: options must be an object
```

**Comment by DenisCarriere** [comment]
`@turf/circle` now uses the new `options` syntax instead of parameters. The docs haven't been updated to reflect this change, also the main Turf is still on v4.0, only some modules have been bumped up to v5.0 for testing purposes.

Reference this for now: https://github.com/Turfjs/turf/blob/master/packages/turf-circle/index.js#L4-L24

**Comment by DenisCarriere** [comment]
Just updated the README's, check out the documentation directly in the `turf-circle` repo (for now, until the website gets updated).

https://github.com/Turfjs/turf/tree/master/packages/turf-circle#turfcircle

**Comment by DenisCarriere** [comment]
Going to close this issue since this will be the same for all v5.0 methods. I updated the docs to reflect the changes, website docs will follow shortly.

**Comment by drewbo** [comment]
Thanks for the quick response @DenisCarriere!

**Comment by DenisCarriere** [comment]
👍
