### ISSUE TITLE
Voronoi polygons module

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1038]
I found that the existing "turf-voronoi" module (https://github.com/Turfjs/turf-voronoi) didn't work at all (and isn't published on NPM), so I made my own: https://www.npmjs.com/package/turf-voronoi-polygons

I'm not really familiar with the contributions model or some of the general thinking, but before I go any further I wanted to check:

- is this something you want in Turf?
- would a wrapper around a D3 function be acceptable?
- if not, is "an unofficial Turf module" an ok way for me to describe my module, or should I remove the Turf name entirely?

**Comment by rowanwins** [comment]
Gday @stevage 

Yeah I think we'd definitely be interested in incorporating a voronoi polygon style function. 

Presuming that d3-voronoi isn't a massive dependency we'd be happy to bring it in (we have used other d3 modules elsewhere successfully so I can't imagine this being a problem).

If you take a look at the[ turf contributing doc](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md) we have a script for starting new modules which pre-populates a whole lot of bits and pieces.

To land the module succesfully we'd probably just want to see it fleshed out with some tests, perhaps broader input support (eg geometries and features), and a bit of jsdoc stuff.

Feel free to sing out if you need a hand with any of that otherwise just throw in a pull request when you're ready.

Cheers
Rowan

**Comment by stevage** [comment]
Thanks. I'm confused about quite a few things like:

- how does the "turf.mymodule" namespacing happen?
- why does Turf use ES modules, when they aren't supported in Node?
- why does Turf use ES modules, when it doesn't even use ES2015? :)

Can you point to an example of a similar-ish non-core module which I could use as a model?

I think I get what you mean by broader input support (presumably, array of Feature, and maybe array of [lng, lat]) - but what kind of "jsdoc stuff" do you have in mind?

(Oh...I just realised part of my confusion was I hadn't realised that all of Turf is in a single repo now. How do the non-core modules get published separately then?)

**Comment by rowanwins** [comment]
Gday @stevage 

Yeah the docs need a bit of updating, there have been a few changes recently

Re the namespacing, we use [lerna](https://lernajs.io/), basically it lets us split our code and publish it as modules, but keep them all in a single repo, very handy for something like turf.

Re ES modules this is a very new change. It enables us to do tree-shaking etc to generate smaller builds. To facilitate this were using [esm](https://github.com/standard-things/esm). And you are right we aren't all in on ES2015 because that would've involved introducing babel. 

turf-bezier is probably a relatively good example to follow, if you take a look at the jsdoc in the index.js you'll get a feel for how we normally structure things,

Anyway hope that helps. We're happy to provide any assistance if you get stuck.

**Comment by stevage** [comment]
Wow, esm. That's...I don't even understand how that can possibly work. Glad to hear that it does though.

Looks like I'm going to learn lots of exciting things about module packaging :) Thanks for the tips, I'll see how I go.

**Comment by stevage** [comment]
Btw how massive is massive? d3-voronoi is 44K of unminified source, no non-dev dependencies.

**Comment by rowanwins** [comment]
minified d3-voronoi is 9kb so I'm comfortable with that :) It's only if we were pulling in 100's of kb's that we'd be concerned. The module could possibly be made smaller if someone wrote it from scratch but I'm sure that would be a big undertaking so if we can leverage something existing we're all for it!

Yeah the `esm` stuff is pretty new to me, @DenisCarriere has been leading that side of things. `esm` comes from the dude who created lodash so it's very reputable.

**Comment by DenisCarriere** [comment]
👍 Thanks for answering those questions @rowanwins.

@stevage Lots of new packaging tools in TurfJS, it is a bit overwhelming at first. One day `import` & `export` will be native to NodeJS and we could drop `@std/esm` (for now it's needed).

The `d3-veronoi` module looks awesome! 👍 It's also written in ES Modules, so it would be very easy to implement in Turf.

9kb is perfectly fine, no one should ever attempt to rewrite this module... it's definitely hard one!

> if not, is "an unofficial Turf module" an ok way for me to describe my module, or should I remove the Turf name entirely?
@stevage Feel free to send your initial PR to Turf, try to copy-paste an existing module from the `master` branch and modify your `index.js` from there. Even if the test cases fail at first, we can sort that out in the PR.

**Comment by DenisCarriere** [comment]
Your proposed module looks pretty straightforward to implement: https://github.com/stevage/turf-voronoi-polygons

Shouldn't take too long to implement.

**Comment by stevage** [comment]
Whew. That was intense. So many undocumented and confusing steps for contributing a module, but really appreciated the help.

Some things I ran into, before I forget:

- The combination of lerna, yarn, ES modules adds quite a bit of overhead.  A brief description of the role of each would be helpful. Even knowing how to run an ES-modulified file in Node (`require ('@std/esm')`) was a bit of fumbling around.
- Explain how `npm test` works, and what the difference between running it in `turf/` vs `turf/package/turf-mymodule` is.
- the `create-new-modules` script hasn't been updated, so it's just a big pitfall for contributors atm. (Copying an existing directory seems to be the safer option.)
- some warnings about how strict the linting rules are and some of the specific requirements.
- why is there an index.d.ts, and how does it have to be structured? (I'd never touched TypeScript before..)
- bunch.js is not mentioned but is a requirement for tests.
- tests will fail if you don't add references to /index.js, /index.d.ts and /package.json
- how /package.json and /package/turf-mymodule/package.json each work
- Running `npm run test` within the turf-voronoi package directory fails
- The checklist steps in the pull request template aren't exactly synchronised with CONTRIBUTING.md.

**Comment by DenisCarriere** [comment]
lol Agreed @stevage That would be a good PR 😉

**Comment by DenisCarriere** [comment]
The creation of a new module needs to have it's own checklist, and we recently revamped the entire code base to ES Modules, so some things are definitely outdated.

Once you've got 1 module in, the other ones aren't too bad... 😄

**Comment by DenisCarriere** [comment]
> So many undocumented

Well... their documented by having the tests fail endlessly, that way we can catch everything until the TravisCI tests finally pass.

Before the tests passed often, however things got missed like modules not being published or methods not being exposed, or files missing from the published repo.

**Comment by DenisCarriere** [comment]
Voronoi module is now implemented, will be released in the next minor release.
