### ISSUE TITLE
Document Yarn dependency

### ISSUE THREAD

**Issue by stevage** [Turfjs/turf#1042]
Just tried to run `npm test` but hit an error (unfortunately lost the exact text now) along the lines of yarn not supporting a particular argument (`--no-mutex-something`?) It turns out I had a very old version of Yarn and upgrading it seems to have got me past that.

But there's no mention of Yarn on the CONTRIBUTING page - and indeed, the commands are given as `npm test` etc.

**Comment by DenisCarriere** [comment]
🤔 I'm pretty sure things should work using `yarn` or `npm`, one tricky thing that might not be mentioned is the use of `lerna bootstrap` when editing multiple modules that are not yet published.

Since we haven't completely published all `v5.0` modules, some of the modules are outdated when you `npm install`, after that you need to create symbolic links between them by using `lerna bootstrap`.

👍 [CONTRIBUTING.md](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md) needs a bit of ❤️

**Comment by stevage** [comment]
I wonder if [this line](https://github.com/Turfjs/turf/blob/e6d22597e0330faa60d93de88a5be41ccf393e70/lerna.json#L3) is the reason that yarn got called (and failed...)? Maybe it would build ok with either no yarn, or recent yarn, but not old yarn.

**Comment by DenisCarriere** [comment]
Oh maybe that's the reason... building `lerna` with `yarn` is needed to have a fast dev environment with shared dependencies.

Old yarn might definitely fail.

**Comment by rowanwins** [comment]
Added a few notes about yarn to the contributing.md - although it probably needs a good overhaul particuarly once the latest rounds of changes are done @DenisCarriere
