### ISSUE TITLE
⚠️ Convert @turf/meta indexes callback params to Objects

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#1099]
## Convert `@turf/meta` indexes callback params to Objects

The NEXT major release we should re-organize the index callbacks using an `Object`.

> ⚠️ This should only be done next MAJOR release v6.0 (not scheduled anytime soon)

**Background:** These indexes have been added to retrace the exact feature/geometry position of the provided GeoJSON.

## Before

```js
coordEach(geojson, (currentCoord, coordIndex, featureIndex, multiFeatureIndex, geometryIndex) => {
  //=currentCoord
  //=coordIndex
  //=featureIndex
  //=multiFeatureIndex
  //=geometryIndex
});
```

## Proposed

Something like this =>

```js
coordEach(geojson, (currentCoord, indexes) => {
  //=currentCoord
  //=indexes.coordIndex
  //=indexes.featureIndex
  //=indexes.multiFeatureIndex
  //=indexes.geometryIndex
});
```

Which allows to do some cool deconstructing like this =>

```js
coordEach(geojson, (currentCoord, {geometryIndex}) => {
  //=currentCoord
  //=geometryIndex
})
```

This would allow us to retrieve any index without "guessing" the parameter position.

**Comment by DenisCarriere** [comment]
@rowanwins Looks like someone had the same idea 👍 https://github.com/Turfjs/turf/issues/1168#issuecomment-350585174

**Comment by tmcw** [comment]
👎 I'm a hesitant -1 here.

* One does not guess turf-meta arguments: there is [documentation](https://github.com/Turfjs/turf/tree/master/packages/turf-meta). This is mostly an internal method, that most people don't need to use. It's reasonable to expect core contributors to read the docs.
* I'd strongly bet that this change would impact turf-meta's performance. The idea of turf-meta is that it ensures support for all variations of GeoJSON, with as close to 'zero' a performance impact as possible. This would likely make it slower, because we'd be creating an object for every single iteration. That seems like a bad trade.

**Comment by smallsaucepan** [comment]
Will close this and #1168 as "not planned". Hasn't been any chatter for some time and suspect this change is no longer on the radar.
