### ISSUE TITLE
Mutability bugs

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#116]
* [ ]  turf-simplify mutates its input #322

I would like turf to treat inputs as purely functional, immutable objects. This is not currently happening in all cases, and could cause unexpected behavior in cases where people are expecting an object to be unchanged by an operation. Most of these issues could be dealt with by cloning the input at the beginning of the function, but I want to be able to do this in a consistent, performant, and resource-sensitive fashion, without relying on lodash's deepClone (since lodash is being removed from turf entirely to improve turf's footprint and compatibility with browserify). 

If anyone has any suggestions for this, let me know. I probably want a module to do this so that ```npm dedupe``` can optimize library size in browserify builds, and we do not end up with a bunch of repeated code in each submodule (DRY, convenience, etc.).

**Comment by tchannel** [comment]
I did some quick benchmarks on this. I tested by using various methods to clone the armenia.json Feature from the Turfjs/turf-intersect fixtures. I compared:

- [node clone](https://npmjs.com/package/clone)
- `JSON.parse(JSON.stringify(geojson))`
- The JSON specific clone function (`cloneJSON`) proposed [here](http://stackoverflow.com/a/17502990/2725626) 


The results were: 

- node clone: 15, 345 ops/sec
- parse+stringify: 53, 958 ops/sec
- cloneJSON: 312, 470 ops/sec

If we can't find an existing module that implements a satisfactory clone option (I looked, not extensively, but didn't find much, definitely not as fast as the cloneJSON option, since it's designed only to work for JSON not arbitrary JS) we could package up our own version of cloneJSON
