### ISSUE TITLE
Error handling in browser

### ISSUE THREAD

**Issue by Spown** [Turfjs/turf#1164]
Am I correct to assume that turf tries never to raise exceptions?

Because every time something goes wrong - I get a stringified version of the error at ``turf.min.js:1``. In most cases it has something to do with turf method arguments so it is ok, but right now I am stumbled upon a very strange behavior, that probably has nothing to do directly with turf and originates somwhere else, but I can't reach and inspect it with the debugger, since there is never an exception raised. Again, if I'm right that is. And if I'm right, could you please either turn this off or introduse some sort of an option to turn it off?

Also it would be helpful to have unmini/uglyfied version of the browser lib to be able to trace errors better. In this case, because of the aforementioned stringification of the error I try was trying to reach it by setting a breakpoint on the line before it occurs and stepping into, but sadly I can't read matrix. Could you please include it into the package?

Thank you.

**Comment by rowanwins** [comment]
Gday @spown,

You are correct in that turf doesn't really have any try/catch style exceptions, that said we'll often throw errors particularly when inputs are incorrect.

We should add the generation of a sourcemap to our [rollup config](https://github.com/Turfjs/turf/blob/master/rollup.config.js) to those built files, it would certainly aid in debugging.

And if additional built outputs are helpful then certainly we are open to supporting them. Rollup certainly makes it fairly straightforward to generate them. We just need to find a way to document all the various possibilities so that people find it obvious as to what to use.

If you are familiar with [Rollup](https://rollupjs.org/) and would like to suggest a config then let us know otherwise we'll see what we can come up with. If you download the whole repo you're welcome to play around with this, that way you can generate yourself a sourcemap really easily straight away rather than waiting for us.

As a general comment our focus in the past few months has probably been on supporting people using specific modules of turf, rather than the entire built package. Web app development is dominated at the moment by build tools like webpack which allow you to only pull in the module or two that they want, rather than the full whack of Turf which is quite heavy. And as mentioned previously we've only recently moved to the rollup approach, so there are definitely some improvements we can make.

Thanks for reporting the issue in a constructive way, much appreciated :)

**Comment by DenisCarriere** [comment]
@Spown I've added UMD support to the "unminified" bundle for both `"main"` & `"module"` (PR https://github.com/Turfjs/turf/pull/1166).

Don't hesitate to re-open this issue if the `"main"` does not work in the browser.
