### ISSUE TITLE
Definition of how to work with bbox?

### ISSUE THREAD

**Issue by strech345** [Turfjs/turf#1179]
Hello,
for me this framework look like, that it is not defined how to work with bboxes. 
Because it will not automatic calculated and if i calculate it, i have to put it by my self to the right place `feature.bbox`. 
A nother problem, its not clear which function use this bbox. For example `booleanWithin `didn't, but `booleanPointInPolygon `does. For me this is not the right way how to work with bboxes.

I would like, that the bbox would be by default automatic calculated and will be used anyway for calculations if it is set. - That means also a property like `ignoreBoundary` is not usefull, because if it set, it should be valid for the geometry and it doesn't make sense to disable it.

**Comment by rowanwins** [comment]
Hi @strech345 

Yes you are correct in that there is inconsistent use of `bbox` across modules. One of the challenges of turf is because of it's modular nature we don't always tackle things consistently, and we don't draw on overarching geometry classes that might normally enforce some of this stuff (which is both a blessing and a curse).

So I can see a few potential actions
- We add an optional parameter to the `@turf/bbox` to specify whether we should add the bbox property to the feature. 
  - Given that bbox can be used to improve the performance of many functions I think we should set the default to true
- One of the challenges with using `bbox` on operations is that there is some overhead in computing them, so for example in `booleanWithin` it may take longer to compute the bounding box and then run the subsequent operation
  - that said I think what we've tried to do in most instances is look for a `bbox` property, and if it's present use it to inform the operation. We may have missed adding this check in some modules.
  - the other issue of course is that this relies on the bbox property being up to date, which means either turf, or developers need to make sure that bbox property is being kept up to date when geometries are altered, again this takes compute time....
    - I think in this case if Turf is altering geometries we should by default blow away a bbox property that exists on a feature.
      - My preference would be that we leave it to users to recalculate bbox, that will keep our modules smaller. How we document this though is a challenge...

Obviously this is one of those trade off situations. Turf tries to be lean and fast which means we don't always implement everything that as a traditional geometry library might. We do however try to provide the right tools for developers to chain together for their requirements. We're open to suggestions as to how we might best do that.

**Comment by strech345** [comment]
@rowanwins, thanks for your replay.

i think, if a calculation get features with bboxes, the new feature should be also get a bbox. Because, in most cases, a bbox could be calculated for the new feature without the geometry only by using the relationship of  the bboxes (difference, union, intersect,...). A post bbox calculation means to iterate the geometry and will cost more time. 
I love the way, that the user don't have to think about the bbox and it will be used in the background to speed up calculations.

**Comment by DenisCarriere** [comment]
For now, I've changed the `@turf/bbox-polygon` to translate down the `bbox` properties to the output since the user is explicitly giving a `bbox`.

Like @rowanwins mentioned, we need to be careful when handling the `bbox` property since this property does not get modified each time a TurfJS operation is used, so the geometry might change but the `bbox` property will not be modified.

As for each individual TurfJS modules to use the `bbox` property or not will be a case by case basis. I believe some of the `@turf/boolean-*` modules are already using the `bbox` property to quickly return `false`, but handling `true` needs a bit more computation.

Closing for now since the scope is a bit too wide as a single issue.
