### ISSUE TITLE
How to use center and lineArc to draw a curved line from PointA and PointB ?

### ISSUE THREAD

**Issue by aziz-boudi4** [Turfjs/turf#1218]
I'm using a `Layer` and a `Feature` from react-mapbox-gl to draw a line from point to point B` ( see screenshot 1)

My goal is to use line-arc and center from turf js in order to have a curved line between point A and point B

I managed to get a curved line, but it's not starting at Point A and it's not finishing at Point B... it is instead drawn in the middle of the map (see screenshot number 2)

Here is my code

```js
     const features = turf.featureCollection([
       turf.point(this.state.startFlying),   // [-122.3811441, 37.6213129]
       turf.point(this.state.destinationFlying),  // [-118.4107187, 33.9415889]
     ]);

    const theCenter = turf.center(features);
    const arcRadius = 5;
    const bearing1 = 25;
    const bearing2 = 47;

    const arc = turf.lineArc(theCenter, arcRadius, bearing1, bearing2);
    const mappedCurvedFlyingCurve = arc.geometry.coordinates;
```

![screen shot 2018-01-08 at 1 17 16 pm](https://user-images.githubusercontent.com/7435015/34693354-06cc7426-f478-11e7-821e-2e57dde9b57c.png)

![screen shot 2018-01-08 at 1 22 10 pm](https://user-images.githubusercontent.com/7435015/34693360-0e9c9a5a-f478-11e7-8fc7-d96e4f285c97.png)

![screen shot 2018-01-08 at 1 22 31 pm](https://user-images.githubusercontent.com/7435015/34693366-13d8f63a-f478-11e7-959d-aaa7d1604177.png)

**Comment by rowanwins** [comment]
If I understand correctly you basically want to create a curved line between your points, keeping the same start and end point. `line-arc` isn't really intended for this. You're probably better off trying to use `great-circle` - see http://turfjs.org/docs/#greatCircle

**Comment by aziz-boudi4** [comment]
@rowanwins Thanks, it's working. Do you know how to adjust the curvature of the Arc? Can we even do that with `great-circle`?

**Comment by rowanwins** [comment]
Unfortunately curvature can't be adjusted with `great-circle`, a great circle is fixed formula.

Another alternative approach might be to use `turf/midpoint` to calculate your midpoint of your existing points, as well as then get their bearing using `turf/bearing`. Then feed the midpoint and bearing into `turf/destination`, as well as your desired offset distance, this will you give you a point that represents the top of your curve. You could then use `turf/bezier-spline` to create a smooth line from your three points (eg start, end and offset midpoint).

It's a bit convoluted sorry but if you get it working feel free to bundle it up as a module and then we can include it in turf for others!

Hope that helps ;)

**Comment by DenisCarriere** [comment]
@rowanwins Great answer! 👍 I think you're spot on with your explanation, @aziz-boudi4 I'd recommend using @rowanwins's last comment, that's how I would do it as well.

**Comment by aziz-boudi4** [comment]
@rowanwins Thanks for the detailed explanation. I will give it a try and I'll keep you posted on the progress. Good idea to bundle it up as a module so that others can use it. I'm sure it's a common use case

**Comment by stebogit** [comment]
Hey @aziz-boudi4, I'm not sure if I have understood your need, but if you want to basically draw an arc between points you could also do something like this:
```js
const p1 = turf.point([-122.3811441, 37.6213129]);
const p2 = turf.point([-118.4107187, 33.9415889]);

const bearingToCenter = turf.bearing(p1, p2) + 90;
const midPoint = turf.center(turf.featureCollection([p1, p2]));
const arcRadius = 1000;

const theCenter = turf.destination(midPoint, arcRadius, bearingToCenter);

const bearing1 = turf.bearing(p1, theCenter);
const bearing2 = turf.bearing(p2, theCenter);

const arc = turf.lineArc(theCenter, arcRadius, bearing1 +180, bearing2 +180);
```
![screen shot 2018-01-11 at 9 20 20 am](https://user-images.githubusercontent.com/12717225/34837757-aa569e3e-f6b0-11e7-935b-8e5e7c2940a5.png)

Clearly the code is not perfect, but it's just a quick draft to give you the gist.

It could actually be useful having this capability of using points instead of bearings to draw the arc.

**Comment by aziz-boudi4** [comment]
@stebogit thank you very much for taking the time to help out.

I got the big picture, but I can't seem to find how to make the line starts at `pointA` and finishes at `pointB` ?

**Comment by stebogit** [comment]
@aziz-boudi4 try using Rhumb modules instead and probably using angles instead of bearing (`@turf/helpers.bearingToAzimuth`) could make calculations easier.

Anyway, `lineArc` uses Turf functions on the spherical plain (namely `destination` and `bearing`), if would be useful to add a 'mercator' option to switch to Rhumb functions.
I tried here to draft the function [here](https://jsfiddle.net/jStefano/bjehhxr7/) and it get closer, but I guess it requires some more work to make it right:
![screen shot 2018-01-20 at 2 44 06 pm](https://user-images.githubusercontent.com/12717225/35188735-6061cadc-fdf0-11e7-9370-303b780c1682.png)

**Comment by savy-91** [comment]
Here is how I did it:

```
drawArc(id: string, start: UniversalPlace, finish: UniversalPlace) {
    const route: LineString = {
      type: 'LineString',
      coordinates: [
        [start.longitude, start.latitude],
        [finish.longitude, finish.latitude]
      ]
    };
    const lineD = lineDistance(route, {units: 'kilometers'});
    const mp = midpoint(route.coordinates[0], route.coordinates[1]);
    const center = destination(
      mp,
      lineD,
      bearing(route.coordinates[0], route.coordinates[1]) - 90
    );
    const lA = lineArc(
      center,
      distance(center, route.coordinates[0]),
      bearing(center, route.coordinates[1]),
      bearing(center, route.coordinates[0])
      );
    this.mapView.addLayer(
      {
        id,
        type: 'line',
        source: {
          type: 'geojson',
          data: lA
        },
        paint: {
          'line-width': 4,
          'line-color': '#FCA526'
        }
      }
    );
  }
```

Example of the result:
![image](https://user-images.githubusercontent.com/6215122/75526707-9097cc80-5a12-11ea-9183-be01702ba0ac.png)

**Comment by cdbusby** [comment]
@savy-91 Thanks for this, did exactly what I needed it to. I can't believe how difficult this was to figure out.

**Comment by crevulus** [comment]
Does anyone know why the destination point seems to be offset, as you can see in [this reply above](https://github.com/Turfjs/turf/issues/1218#issuecomment-359208040)?

As you can see there, the end of the line doesn't quite match up with the end marker (in LA), and instead ends up in the sea. In my experience, this problem gets worse the further the line distance. In the screenshot below, the line should end up somewhere in Hawaii:
![Screenshot 2021-06-18 at 10 59 31](https://user-images.githubusercontent.com/50107046/123621717-6b33f200-d803-11eb-8e22-044c48aa8136.png)

The code is taken pretty much exactly as @savy-91 described:

```js
const useRouteLine = ({ originAirport, destinationAirport }: UseRouteLineProps) => {
  const [curved, setCurved] = useState<any>([]);
  useEffect(() => {
    if (originAirport.airport_name && destinationAirport.airport_name) {
      const start = [parseFloat(originAirport.longitude), parseFloat(originAirport.latitude)];
      const end = [
        parseFloat(destinationAirport.longitude),
        parseFloat(destinationAirport.latitude),
      ];
      const distance = turf.distance(start, end);
      const midpoint = turf.midpoint(start, end);
      const bearing = turf.bearing(start, end) - 90;
      const destination = turf.destination(midpoint, distance, bearing);

      const curvedLine = turf.lineArc(
        destination,
        turf.distance(destination, start),
        turf.bearing(destination, end),
        turf.bearing(destination, start),
        { steps: 128 },
      );
      setCurved(curvedLine);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [originAirport, destinationAirport]);

  return curved;
};
```

```js
const curvedLine = useRouteLine({ originAirport, destinationAirport });
  const [route, setRoute] = useState<FeatureCollection<LineString>>({
    type: 'FeatureCollection',
    features: [curvedLine],
  });
```

(using react-map-gl)
```js
<Source id="map-line" type="geojson" data={route}>
    <Layer {...lineLayer} />
</Source>
```

**Comment by stebogit** [comment]
@crevulus I believe the issue is, once again, projection/spherical distortion, i.e. working with euclidean (plane) distance and bearing instead of [Rhumb](https://en.wikipedia.org/wiki/Rhumb_line) functions. In your case the distances are so big, compared to @savy-91's example, that the final result is way off.

Look at [this example](https://turf-sandbox.netlify.app/?gist=bc5c729d0d89e25d60c2c412bb8d6357), I believe it works much better, although still not 100% accurate:
```js
const start = [-118.30078125, 33.925129700072]; // LA
const end = [-157.6318359375, 20.92039691397189]; // Hawaii
// rhumb functions
const radius = turf.rhumbDistance(start, end);
const midpoint = turf.midpoint(start, end);
const bearing = turf.rhumbBearing(start, end) - 89; // <-- not 90˚
const origin = turf.rhumbDestination(midpoint, radius, bearing);

const curvedLine = turf.lineArc(
  origin,
  turf.distance(origin, start),
  turf.bearing(origin, end),
  turf.bearing(origin, start),
  { steps: 128 }
);
```

![Screen Shot 2021-06-29 at 5 07 48 PM](https://user-images.githubusercontent.com/12717225/123883002-db726e80-d8fc-11eb-88f2-fe3070473762.png)

**Comment by hussi-azam** [comment]
Any help for Android users with Turf and rhumb functions ? :D

**Comment by Arttii** [comment]
Hi,

I was wondering if somebody has a tip on how to draw the arc counterclockwise? I cannot seem to figure it out.

Thanks!

**Comment by randomprogramming** [comment]
None of the solutions here helped me! I just can't get the ending points to all point to the same destination:

<img width="706" alt="image" src="https://github.com/Turfjs/turf/assets/48063901/46cb6ad1-ce82-459b-ad3c-3d09a57e5fa8">

This is using @stebogit 's solution, which was the closest one, but I just can't get them to line up at least closeby and it's driving me crazy.. Has anyone managed to find another solution??

**Comment by mausworks** [comment]
This is the solution I ended up using; it sets the "height" of the curve to the maximum of the greatest distance of either the latitude or longitude and the "width" of the curve to the center.

It should work like this (where `s` = start, `c` = curve/center, `e` = end), but imagine a bezier curve instead of straight lines.

```
c - e
|
s
```

```
    e
    |
s - c
```

```
s - c
    |
    e
```

I'm not sure whether the code does this exactly, but it LGTM. 🤷 

```tsx
function buildArcLine(
  [startLng, startLat]: [number, number],
  [endLng, endLat]: [number, number]
) {
  const midLng = (startLng + endLng) / 2;
  const midLat = (startLat + endLat) / 2;
  const distLng = Math.abs(startLng - endLng);
  const distLat = Math.abs(startLat - endLat);
  const curveLat = distLat < distLng ? endLat : midLat;
  const curveLng = distLng < distLat ? endLng : midLng;

  return bezierSpline(
    {
      type: "Feature",
      properties: {},
      geometry: {
        type: "LineString",
        coordinates: [
          [startLng, startLat],
          [curveLng, curveLat],
          [endLng, endLat],
        ],
      },
    },
    { resolution: 2500 }
  );
}
```


> Note: You can use `turf.midpoint` if you want better precision, but since I'm not working with great distances,
this works just fine:


In practice, this is how it looks: 

<img width="755" alt="image" src="https://github.com/Turfjs/turf/assets/8259221/2c526820-4292-4591-966f-1aee556be4a6">

<img width="738" alt="image" src="https://github.com/Turfjs/turf/assets/8259221/a064be58-c7ff-4d63-a844-24324f761aa2">

<img width="401" alt="image" src="https://github.com/Turfjs/turf/assets/8259221/bb4f062d-c276-44f7-824c-18267df44fa2">

Mentioning https://github.com/Turfjs/turf/issues/2591 here, since it's related.
