### ISSUE TITLE
Equivalent to squareGrid for rectangles

### ISSUE THREAD

**Issue by adam3039** [Turfjs/turf#1251]
I need to split a bounding box into rectangles (specify a length & width of the grid cell). Is there any way to achieve this with existing tools, or potentially a feature that could be added.

**Comment by rowanwins** [comment]
Hi @adam3039 

We dont currently have this functionality although it would probably be relatively simple to implement. 

If you'd like to have a go at implementing it take a look at the source code from the [square-grid](https://github.com/Turfjs/turf/blob/master/packages/turf-square-grid/index.js) module and that should get you on your way, we'd happily accept a pull request for a new module. Otherwise it'll probably be a little while before any of the core team have any time to take a look at it.

Cheers
Rowan

**Comment by rowanwins** [comment]
Closing in favour of #1403 and #1405
