### ISSUE TITLE
Documentation: Supporting "meters" unit

### ISSUE THREAD

**Issue by ozomer** [Turfjs/turf#1298]
Hi,
All operations that accepts units of "degrees, radians, miles, or kilometers" can also accept "meters".
One of our developers called `distance` with unit "kilometers" and divided the result by 1000, because the documentation did not specify that it supports meters too.

Minor issue, not critical...

**Comment by rowanwins** [comment]
Thanks for the report @ozomer , good pickup!

**Comment by DenisCarriere** [comment]
Meters is included in the source code:

https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.mjs#L10-L11
https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.d.ts#L20

I agreed that we could add "meters" in the docs, however we shouldn't include every single unit of measurement in the docs (keep it short & simple).

**Comment by andrewharvey** [comment]
I've always been converting meters to kilometers since I didn't know meters is supported too.

> I agreed that we could add "meters" in the docs, however we shouldn't include every single unit of measurement in the docs (keep it short & simple).

I disagree, the documentation should document all supported options.

**Comment by mfedderly** [comment]
I'd love to have the documentation be accurate everywhere but that involves a bunch of duplication that our docs aren't setup for right now. As a half measure, the typescript types reference the canonical list, so any typescript consumers will now get the full list.

**Comment by smallsaucepan** [comment]
Would this be a suitable approach? Rather than list all options on every function, add a centralised list and embed a link in the Description field. Publicises that other options are available without cluttering up the API documentation.

<img width="562" alt="Screenshot 2023-08-18 at 3 02 15 pm" src="https://github.com/Turfjs/turf/assets/5403628/ac394f21-b325-4208-9228-82234ac9e31e">

The full list:

<img width="551" alt="Screenshot 2023-08-18 at 3 02 24 pm" src="https://github.com/Turfjs/turf/assets/5403628/64a7f80f-de30-4c9f-9d59-ae6212a418d3">

Would do the same for area related units.

**Comment by twelch** [comment]
@smallsaucepan I'm open to this approach if you want to give it a try.  Holler if you have questions

**Comment by smallsaucepan** [comment]
The Units typedef now has it's own page on the website: https://turfjs.org/docs/next/api/types/Units As we update documentation for each method they'll begin to link to the full list of options automatically.
