### ISSUE TITLE
centerOfMass doesn't return Feature for point input

### ISSUE THREAD

**Issue by hyperknot** [Turfjs/turf#1385]
centerOfMass is inconsistent in it's output. 

In theory, it should always return Feature<Point>, per specifications.
In practice, it might return a geometry without a feature, when the input is a point geometry.
Tests are missing for this case as well.

Codesandbox:
https://codesandbox.io/s/0381rqqzo0

**Comment by rowanwins** [comment]
Hi @hyperknot 

Thanks for the report. So the error is in [this line](https://github.com/Turfjs/turf/blob/master/packages/turf-center-of-mass/index.ts#L28) where a point input simply returns the point, rather than forcing it to be a feature if it's only a geometry. It should be pretty simple to write a check and if it's a geometry wrap it in a feature. If you'd like to have a go feel free, otherwise one of the team will get there eventually.

Cheers
Rowan

**Comment by hyperknot** [comment]
@rowanwins thanks I've solved it my side, I just wanted to report it here. (Also, it really is a perfect first PR).
