### ISSUE TITLE
booleanPointInPolygon behavior with circle polygon

### ISSUE THREAD

**Issue by YujiHamada** [Turfjs/turf#1442]
I would like to know design of method of booleanPointInPolygon.
I tried booleanPointInPolygon with circle polygon, like below image. The star is the coordinates.
<img width="580" alt="default" src="https://user-images.githubusercontent.com/16176977/42870746-9b33988e-8ab3-11e8-95f0-e75e69ddbf8a.png">
In this situation, booleanPointInPolygon returns true.

But I also tried with almost circle polygon.
<img width="517" alt="default" src="https://user-images.githubusercontent.com/16176977/42870818-cc34bf12-8ab3-11e8-9ff8-e776cda18dab.png">
booleanPointInPolygon returns false.

I expected both case returns false, because they don't touch polygon.
Is this in the specifications?

**Comment by rowanwins** [comment]
Hi @YujiHamada 

Can you provide the geometries you are passing in, or provide a jsfiddle etc. Bit hard to debug without seeing what you're doing properly.

THanks
Rowan

**Comment by YujiHamada** [comment]
@rowanwins 
https://gist.github.com/YujiHamada/9788bc747ee351c681a3b0b88d2d12f4
This is my test source.
Thanks.

**Comment by stebogit** [comment]
@YujiHamada the result seems correct. Maybe this images make it more clear:

![screen shot 2018-07-18 at 6 32 56 pm](https://user-images.githubusercontent.com/12717225/42916288-5d34a3f6-8ab9-11e8-8fac-739e59fa19e7.png)
![screen shot 2018-07-18 at 6 32 49 pm](https://user-images.githubusercontent.com/12717225/42916289-5d467d2e-8ab9-11e8-9295-df38d8ee731a.png)

Your `inside_point` is not inside the `almost_circle_poly`, but it is instead inside the `circle_poly` one.

If I get right what you need, probably you want to use something like `@turf/concave` on the set of points composing your polygon so that you generate a concave polygon "external" to that; then check if your point is inside that polygon.

**Comment by YujiHamada** [comment]
@stebogit Thank you so much. I understand this is working as expected.
I would like to try other method.
I'm sorry for my poor English and code, Thank you!
