### ISSUE TITLE
nearestPointOnLine broken on vertical line segments

### ISSUE THREAD

**Issue by msbarry** [Turfjs/turf#1514]
nearestPointOnLine exhibits strange behavior when the line is near-vertical.

For example in this jsfiddle the line goes from [-40,50] to [-40,60], the point is [-40.01,56] and turf returns the nearest point as [-40,~55.3]: https://jsfiddle.net/hdumty60/

I tried playing with the code a bit and the issue went away if I changed nearest-point-on-line to use rhumb destination, not sure if that is an ideal solution though.

**Comment by rowanwins** [comment]
Hi @msbarry 

Thanks for the report. Yeah we've experienced similar with the `along` module, particularly when traversing large distances. In the `v7` branch I've switched to using `rhumb-destination` for the along module.
 
[This page](https://www.movable-type.co.uk/scripts/latlong.html) contains some of the information behind the idea of rhumb calculations. I can't claim to be a maths & geomatics nerd but _i think_ rhumb calculations are a better fit for these modules.

Cheers
Rowan

**Comment by smallsaucepan** [comment]
Hi @msbarry. There is a fix on the way that should address this. Realise it's been a while, though if you are still interested please keep an eye on this issue. For reference, black pin is your target point, red pin is the incorrect nearest point you reported, and green will be the new nearest point once the fix is rolled out.

![Screenshot 2024-09-21 at 1 23 38 PM](https://github.com/user-attachments/assets/0fe7393c-c20d-457c-b5dc-7bb390173f1e)
