### ISSUE TITLE
@turf/intersect to work with MultiPolygon

### ISSUE THREAD

**Issue by Zymbar** [Turfjs/turf#1543]
In deprecated versions of turf's package, namely turf/intersect, input features could be either Polygon or MultiPolygon. In my typescript project I have a collection of features and each of these features can be a Polygon or MultiPolygon. Is there any fast method to use @turf/intersect in this case, or simply, I have to iterate over each of the polygons in case if I encounter a Multipolygon?

**Comment by rowanwins** [comment]
Hi @Zymbar 

Can you provide a snippet of how you'd ideally like to use `intersect`? 

Are you basically saying you want to pass in a single feature collection as 1 argument, and get the intersect of all the features, rather than passing in 2 arguments (being 2 features)?

This should be doable with the new intersect algorithm in the v7 branch, although I probably need to make some tweaks to allow user to only pass in a single argument...

Cheers
Rowan

**Comment by Zymbar** [comment]
Hi rowanwins,
Thanks for your interest. Below there is a snippet of my method which works under deprecated version of turf/intersect 3.0.12. 
area.feature which is used in turfIntersect method is either a Polygon or MultiPolygon. Perfectly, I'd like to keep this code working in the latest version, but it seems to be impossible.

![screenshot 11](https://user-images.githubusercontent.com/26443476/49494700-cfb38e00-f860-11e8-8684-a902de77a39d.png)

**Comment by lucaluca** [comment]
It looks like @Zymbar is looking for the intersection of two features, one or both of which might be a MultiPolygon. I think the way to do this is convert any MultiPolygons to an array of Polygons and iterate over all the pairs, then add up any intersections into a MultiPolygon. 

In my own work, I use `intersect` to calculate the area of the intersection of two features, so I don't care how many pieces there are. All I needed to do to make it work with MultiPolygons was convert each of the two features into an array of their individual polygons, then iterate over each. I break down the MultiPolygons as follows:
```javascript
if (feature1.geometry.type === 'MultiPolygon'){
    pieces = feature1.geometry.coordinates.map(c => turf.polygon(c))
  } else {
    pieces = [feature1]
  }
```
(repeat for feature2, then iterate over the "pieces" of each, and sum the intersections)

Providing the code instead of a PR because I don't know how others use `intersect` or what their expected result from MultiPolygons would be. But this logic worked for me.

**Comment by rowanwins** [comment]
This now works since v6.3.0
