### ISSUE TITLE
Intersect of line when the lines are extended

### ISSUE THREAD

**Issue by mohammedzamakhan** [Turfjs/turf#1551]
Is there a way to find the line intercepts of these multiline if they were to be extended? How would I be able to achieve getting the intersect point using turf?
<img width="484" alt="screen shot 2018-12-14 at 12 17 09 pm" src="https://user-images.githubusercontent.com/2327532/50020096-81a63500-ff9a-11e8-8aea-74ec5aba3799.png">

**Comment by stebogit** [comment]
@mohammedzamakhan  just an idea:
- using [`@turf/bearing`](http://turfjs.org/docs#bearing) with the first and last point of a line you can get its direction
- create a new longer `LineString` with the same calculated direction so that it intercepts the other one: you can measure the distance between the lines using [`@turf/point-to-line-distance`](http://turfjs.org/docs#pointToLineDistance) using one end point and [`@turf/destination`](http://turfjs.org/docs#destination) to generate the coordinates
- then use [`@turf/line-intersect`](http://turfjs.org/docs#lineIntersect) on the new line and the target line to find the intersection point

Let me know if that works 😃

**Comment by morganherlocker** [comment]
Looks like there were some good suggestions here. Hope you found a solution @mohammedzamakhan!
