### ISSUE TITLE
Add  function that translates DE-9IM strings to humans

### ISSUE THREAD

**Issue by ppKrauss** [Turfjs/turf#1562]
Many spatial query systems offers option to  process [DE-9IM  strings](https://en.wikipedia.org/wiki/DE-9IM), but that strings are "ugly for humans", so seems that they are not usefull... But they are important (!).  The problem was explained years ago [here](https://gis.stackexchange.com/q/26124/7505), and an exemple of solution (for PostGIS) was published in the same year, today is [here, named "st-relate-summary"](https://github.com/ppKrauss/postgis-st-relate-summary). 
  
**Suggesting both**: to offer a [ST_Relate()](https://postgis.net/docs/ST_Relate.html) equivalent in Turf, and to offer a translator (the *st_relate_summary()*  function)

**Comment by rowanwins** [comment]
Hi @ppKrauss 

Yeah we haven't gone down the route of implementing DE-9IM strings anywhere in turf at the moment. The closest we've got currently is our set of boolean modules which attempt to provide similar functionality although they just return the true or false for a particular operation (eg intersects). 

So unfortunately we're a long way off having proper DE-9IM support, at the moment we don't even need to worry about translating strings because we don't have them :)

Does that make sense?

**Comment by ppKrauss** [comment]
Hi @rowanwins, thanks. Yes, as I see no "ST_Relate() equivalent in Turf", as you say "... haven't gone down the route of implementing DE-9IM strings (...) long way off having proper DE-9IM support".  Yes, make sense for Turf, that need focus on demand and lightweight implementations.

After `v7` I return here checking possibility of "lightweight DE-9IM", that is the 9IM matrix and can be obtained by boolean modules.
