### ISSUE TITLE
TopologyException: found non-noded intersection between LINESTRING

### ISSUE THREAD

**Issue by mnvx** [Turfjs/turf#1575]
How to reproduce:

https://jsfiddle.net/mnvx/6tfcan1b/

![image](https://user-images.githubusercontent.com/829880/52150559-6940c580-2681-11e9-8626-4ce1fd5c06e9.png)

I has built union of 3 polygons. And I try to intersect them with 4th. As you can see on screenshot, problem caused by very small triangle (looks like point) in center of image. Coordinates of triangle:

```
[41.71762030205352, 45.327609463396044]
[41.71762049999992, 45.32760549993015]
[41.71762039674412, 45.327609678130536]
[41.71762030205352, 45.327609463396044]
```

Will be grateful for help!

**Comment by morganherlocker** [comment]
This error message is reported when a polygon edge crosses itself in a self-intersection. This is not considered a valid feature in Turf world; only geometries compliant with OGS simple features are supported. I'm having a little trouble viewing this feature in geojson.io since it is so small, but I suspect it either crosses itself or is so small that precision fuzziness is coming into play.

**Comment by mfedderly** [comment]
Given that this is a jsts limitation, we can probably close this at this point.
