### ISSUE TITLE
Grids generation problems on the whole sphere

### ISSUE THREAD

**Issue by chasset** [Turfjs/turf#1598]
First, I would like to thank you for your work. It is a great package for spatial analysis.

I try to get a grid of points on the whole sphere using http://turfjs.org/docs/#pointGrid.

This geoJSON (https://gist.github.com/chasset/2189b121941234acf3dbb90b1b0f111b
) is produced by :

```
turf.pointGrid([-179,-89,180,90], 100)
```

I also tried the following example. It doesn't produce any feature :

```
turf.pointGrid([-180,-90,180,90], 100)
turf.hexGrid([-179,-89,180,90], 100)
turf.squareGrid([-179,-89,180,90], 100)
```

**Comment by rowanwins** [comment]
Hi @chasset 

Thanks for the report, it's surprising that this hasn't been reported before!

I suspect the problem is[these lines](https://github.com/Turfjs/turf/blob/master/packages/turf-point-grid/index.ts#L54-L57) where we calculate the distance between the bounding box points, it's finding the shortest distance around the globe when you want to travel right around the globe.

Cheers
R

**Comment by wangzhidavid** [comment]
Thank you for your work. It is a wonderful package. But i have the same problem. I tried multiple sets of data. It doesn't produce any feature :
turf.pointGrid([-169, -80, 139, 80], 10), 

I also looked at the conversion function code, but could not find the logic problem.Whether the minimum value is considered to be limited.It's better to specify the minimum value in more detail.

Looking forward to your reply.Thanks!
