### ISSUE TITLE
Feature proposal: `randomPoint` can be passed polygonal data rather than just bbox

### ISSUE THREAD

**Issue by rossbernet** [Turfjs/turf#1640]
Hopefully this is the appropriate place to make a feature proposal request/suggestion. If not, my apologies. Much respect for yalls work on turf! It's great.

It'd be great to generate random points by polygonal (geojson) rather than just a bounding box. 

What got me thinking about this was visualizing population changes based on census data. Something [like this](https://demographics.coopercenter.org/racial-dot-map) -- scale is probably beyond turf, but this concept is not.

And I suppose this could apply to all the random feature generators. And I'm also sure yall have thought about this, but out of curiosity I won't just delete the issue just yet..

**Comment by rowanwins** [comment]
Hi @rossbernet 

Sorry for the super-slow reply on this.

This can be achieved using the existing `point-on-feature` module
https://turfjs.org/docs/#pointOnFeature

Hope that helps

**Comment by hoshmn** [comment]
@rowanwins We would also find this useful for our project. `pointOnFeature` is helpful to know about, but wouldn't work for us because it always returns the same point for a given polygon.

Context: [Our map](https://github.com/Hyperobjekt/ddk-map) has millions of points, distributed randomly within the census tracts they correspond to. We currently do this by generating a random point in the bbox of the tract, then checking whether it landed in the tract using `turf.booleanPointInPolygon` (and trying again if it didn't). The problem is we have to put a cap on the number of "attempts" and sometimes don't end up with a point.
