### ISSUE TITLE
feature request: geohash

### ISSUE THREAD

**Issue by drewda** [Turfjs/turf#168]
@morganherlocker not sure if this would fit into your plans, but I'd find geohash encoding and decoding a useful addition to the turf collection. It's something I often use for indexing and for producing semi-readable output.

c.f. https://github.com/sunng87/node-geohash

**Comment by rowanwins** [comment]
Im going to close this due to inactivity and given that we decided to not keep the turf/rbush module in favour of releasing it as [geojson-rbush](https://github.com/DenisCarriere/geojson-rbush). 

As mentioned by @morganherlocker the idea of indexing is beyond the scope of Turf (although we very much recognise it's usefulness and where relevant we'll use it within our modules).
