### ISSUE TITLE
length and nearestPointOnLine - accuracy

### ISSUE THREAD

**Issue by sweco-sekrsv** [Turfjs/turf#1726]
I cant figure this on out. Have a look at this example:
https://jsfiddle.net/krillmcrawl/swe67ncv/10/

Move the mouse along the line and check the console. 

The actual lenght of the line is 4367.02(FME) or 4367.078(Qgis)
The lenght reported from Turf is 4353.6 (13 meter difference seems quite far off)

In the example I have generated stations lines every 10 meters(for easier debugging). As you can see the turf.nearestPointOnLine reports the correct measures in the beginning of the line but after a while it starts "drifting". At station line 60 it turf reports 50.8 and further in at 850 turf reports 847.3 and even further in at 2660 turf reports 2651. 

The accuracy it not quite there. Is there a setting somewhere that I can use to increase accuracy of the length and nearestPointOnLine calculations?

Thanks. Kristian

**Comment by zazagag** [comment]
Not sure is it the same problem, but if we have point from "nearestPointOnLine" and check it with "booleanPointOnLine", we wil get the "false" mostly. Mayby I am missing something in the documentation, but think what both functions are should be connected. I mean, if we get "nearestPointOnLine", we can prove it by using "booleanPointOnLine".
I am changed @kristiansvenssonwsp [fiddle](https://jsfiddle.net/zazagag/1kpvxcwm/5/) a little bit to show this behaiver.

**Comment by ngottlieb** [comment]
@zazagag I'm running into this same problem, kind of problematic as I need to generate a point on a multiline then figure out which segment of the multiline it's on.

**Comment by Appkidd** [comment]
Also seeing this issue. `nearestPointOnLine` and `booleanPointOnLine` should surely be connected as described above.

**Comment by smallsaucepan** [comment]
This could well be the difference between spherical and ellipsoidal calculations. Using the two different methods in geopy produces the results mentioned above: using great_circle gives (4353m) vs geodesic (4367).

Have opened discussion #2470 on the best way to go forward. One option would be to port geopy's distance formula to Turf. However am seeking advice on which technique should become the default if we offer multiple options.

**Comment by smallsaucepan** [comment]
Hi @JamesLMilner @rowanwins @twelch . Will take a look at this if you'd like to assign my way.

**Comment by smallsaucepan** [comment]
The length accuracy part of this should be addressed by #2476. Use needs to pass in the appropriate ellipsoid for underlying distance() calculation to use.

**Comment by smallsaucepan** [comment]
@sweco-sekrsv. At the moment fixing the length issue will have to stay on the back burner. Turf is already using a mix of planar and spherical calculations, and adding spheroidal also ... 🤯 Our focus is on making Turf internally consistent first, then look at parity with other tools once that's stable.

@zazagag, @ngottlieb, @AppKidd nearestPointOnLine was making inaccurate calculations, as was booleanPointOnLine. So they were both wrong, and in different ways, which is why they weren't matching up. A fix for nearestPointOnLine should arrive soon, and then after that will move on to booleanPointOnLine.

Given this issue covers a couple of different modules and outcomes, will close based on the `length` module being "not planned". nearestPointOnLine is covered by #1878, and booleanPointOnLine by #1362.
