### ISSUE TITLE
TypeScript: Argument of type 'BBox' is not assignable to parameter of type 'LngLatBoundsLike'

### ISSUE THREAD

**Issue by allthesignals** [Turfjs/turf#1807]
I'm seeing this TS error but I don't understand why they're incompatible:

> Argument of type 'BBox' is not assignable to parameter of type 'LngLatBoundsLike'

Here's the BBox type: https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/lib/geojson.d.ts#L47-L49
Mapbox-GL type: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L48

Am I looking at the wrong type definitions? 

Versions:
    "mapbox-gl": "^1.6.0",
    "@turf/bbox": "^6.0.1",

More context:

Some feature: https://gist.github.com/allthesignals/4f30a427e0ccdb4b1e86d8b01f9c76f5

```
    const BBox = turfBbox(polygon);

    map.fitBounds(BBox, {
      linear: true,
      duration: 0,
    });
```

Throws: Argument of type 'BBox' is not assignable to parameter of type 'LngLatBoundsLike'

**Comment by allthesignals** [comment]
Able to get around it like this:

```
    const [x1, x2, y1, y2] = turfBbox(polygon);

    map.fitBounds([x1, x2, y1, y2], {
      linear: true,
      duration: 0,
    });
```

But afaict this is the same as the type definition: `[number, number, number, number]`

**Comment by rowanwins** [comment]
Turf sometimes uses different typescript definitions than the standard geojson ones (don't ask me why), this can be particularly problematic when dealing with other libraries which have ts definitions sorry :(

**Comment by twelch** [comment]
I haven't look at what the Turf types were exactly at the time of this issue posting but as of now they are incompatible because a BBox in Turf can be either a Box2D or a Box3D, and a LngLatBoundsLike only accepts the equivalent of a Box2D.  

BBox in turf (as of now):
```
export type BBox2d = [number, number, number, number];
export type BBox3d = [number, number, number, number, number, number];
export type BBox = BBox2d | BBox3d;
```

Mapbox:
```
type LngLatBoundsLike = LngLatBounds | [LngLatLike, LngLatLike] | [number, number, number, number] | LngLatLike;
```

The error reporting has gotten better in Typescript, I think now it would give your more details.  Since your variable could be Box3D (even if it's not), it won't allow it.  Hope that helps.
