### ISSUE TITLE
turf.along has a lower limit for distance turf.along(line, 0.090315176)

### ISSUE THREAD

**Issue by nsharrok** [Turfjs/turf#1808]
turf. along can't handle distances less than about 90 meters along this line.
```
let line = { "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates": [   
        [ -36.63413066873923,   145.71979676718612 ],
        [ -36.63505618282082,   145.72007038706357 ]
     ]
  }
};
let dist = 0.090315176;
let pointa = turf.along(line, dist);
dist = 0.090315175;
let pointb = turf.along(line, dist);
```
pointa = [ -36.63505618282082, 145.72007038706357]
pointb = [ -36.6350561828117,  34.27992961293912]

is this correct behaviour? 
What would be a workaround?

**Comment by nsharrok** [comment]
Here is a workaround.
90 is an arbitrary number with no particular merit other than it is bigger than the distances I want to work with and it is lower than 180. 
```
function along (line, dist, options) {
  let point = turf.along(line, dist, options);
  if (Math.abs(line.geometry.coordinates[0][1] + -point.geometry.coordinates[1]) > 90) {
    point.geometry.coordinates[1] = -point.geometry.coordinates[1] + 180;
  }
  return point;
}
```
pointa = [ -36.63505618282082, 145.72007038706357]
pointb = [ -36.6350561828117, 145.72007038706087]

Loos like a bug to me.

**Comment by rkaravia** [comment]
It looks like your GeoJSON has coordinates in the order `[latitude, longitude]` instead of `[longitude, latitude]`.

One way to quickly spot this problem is to copy-paste the GeoJSON into [geojson.io](http://geojson.io).

Unfortunately the lon/lat order is [not always the same everywhere](https://macwright.org/lonlat/).

If you flip the order of coordinates, `turf.along()` works as expected.

**Comment by rowanwins** [comment]
Thanks for resolving @rkaravia
