### ISSUE TITLE
In some cases `pointsWithinPolygon` is not returning all features

### ISSUE THREAD

**Issue by AScripnic** [Turfjs/turf#1826]
https://jsfiddle.net/8w9dbpvm/2/

as you can see in the example above I have 2 different points with exactly same behavior.
In one scenario the returned value is 0 and in another 1 (which is correct)

**Comment by smallsaucepan** [comment]
Suspect this is because point `a` is above 90 north latitude, so past the pole and literally off the map. I don't think Turf functions are expected to work with values that stray outside -180 / 180 longitude or -90 / 90 latitude.

```javascript
const a = [11.6711, 104.063];
const b = [31.7475, 35.4756];
```

Closing, though please reopen if this doesn't explain what OP was seeing.
