### ISSUE TITLE
Latest release not available at posted endpoint

### ISSUE THREAD

**Issue by kuanb** [Turfjs/turf#1875]
In Turf docs, under https://turfjs.org/getting-started, it indicates that one can require Turf from the following endpoint: https://npmcdn.com/@turf/turf@6.2.0-alpha.1/turf.min.js

![image](https://user-images.githubusercontent.com/6053396/77714709-ef5f5000-6f96-11ea-8a4a-1ed85b11d8a0.png)

At present, that endpoint returns: ```
Cannot find "/turf.min.js" in @turf/turf@6.2.0-alpha.1```

**Comment by vincentsarago** [comment]
Same 😢. Any idea what's going on? I've check Travis log and couldn't find anything

**Comment by rowanwins** [comment]
Due to some changes in packaging it's now at 
https://npmcdn.com/@turf/turf@6.2.0-alpha.1/dist/turf.min.js

**Comment by rowanwins** [comment]
Turns out this broke all the docs :(

**Comment by vincentsarago** [comment]
@rowanwins I don't mean to be a pain in the ... but this change is kind of sad. It breaks every web page I've done where I use turf 🙁. To be honest this is a kinda unexpected change especially for an alpha release !

**Comment by rowanwins** [comment]
Hey @vincentsarago 

Sorry about that, we've just gotten a new contributor on board and this was our first release in years!

Unfortunately with those cdn links if you don't use a named release just picks out the most recent release, and because we changed the location of `turf.min.js` it has freaked.

The old version you've would've been hitting is still available at 
https://unpkg.com/@turf/turf@5.1.6/turf.min.js

@mfedderly - we'll need to have a think about this because this is breaking change. Perhaps even as a temporary measure we can put the compiled output back in the root dir as well.

Cheers
Rowan

**Comment by rowanwins** [comment]
The other thing to mention is that using a CDN hosted version of a library is a somewhat risky option for a production app. Bundling in your dependencies into your application is a more standard low risk approach as you're less likely to get hit by stuff like this.

**Comment by rowanwins** [comment]
Hi @kuanb & @vincentsarago 

We've amended the npm package so that the latest points back to the older version but doesn't change the dist directory so all old CDN links should now work again.

**Comment by vincentsarago** [comment]
thanks a lot @rowanwins this is really appreciated 🙏 
Awesome work

**Comment by mfedderly** [comment]
For anyone who winds up reading this ticket later, the root of the problem was that the CDN's will use whatever gets assigned the `latest` dist-tag. In the publishing of 6.2.0-alpha.* we should've specified the dist-tag when using lerna to publish, because the default dist-tag is `latest`, even for versions that are clearly prereleases.
