### ISSUE TITLE
Is it safe tu use Turf as a 2d geometry library

### ISSUE THREAD

**Issue by aalexgabi** [Turfjs/turf#1891]
I need to do 2d geometry operations. I didn't find any good JS library that has all the functionalities that I need or they don't work as expected (If you know a really good 2d geometry library please share).

I need operations like:
- find center of a rectangle/ellipse
- rotate a shape
- find the overlap polygon between two polygons
- find the intersection between a rotated ellipse and a rotated rectangle
- calculate the ration between the area of an intersection of two shapes and each of the shapes (to find if the overlap area is greater than 50% of the surface of one of the shapes)

It seems that Turf has all the features that I need except for calculating areas (because it uses meters instead of square pixels).

I was worried that the coordinate system would pose problems because of latitude and longitude range (having coordinates like 4000,5640 etc). It seems that Turf does not care if the numbers are not valid latitudes and longitudes.

Is it safe to use Turf as a geometry library as long as I don't use it to calculate areas? It seems to me that areas are non linear due to the earth projection so it won't be reliable even for calculating ratios between areas (because some areas are "larger" than others depending on their position on the coordinate system).

**Comment by rowanwins** [comment]
HI @aalexgabi 

It probably depends a little on the operation/module that you use. Some probably perform a bit slower because they are geared towards using with a sphere so it's adds a bit of complexity, this might affect things like distance, area, direction etc although you'd probably need to assess on a module by module basis.

On the whole though for the operations you've listed TurfJS is probably fine.

I've not come across any really complete geometry libraries in the JS world. There are bits and pieces scattered around the place.

Hope that helps
Rowan

**Comment by aalexgabi** [comment]
@rowanwins Thank you for your answer. It seems that it may not be 100% reliable if I use any function from the documentation without testing it first which may add a lot of work/risk.

For others that may be interested I came across `paper.js` recently. It has all the features that I needed and more. It also allows using only the math part and disabling the canvas if you don't need rendering using `paper.setup([100, 100])`.
