### ISSUE TITLE
requiring @turf/circle returns an object instead of a function

### ISSUE THREAD

**Issue by lamesjim** [Turfjs/turf#1932]
```
const circle = require('@turf/circle)
console.log(circle)
// { default: [Function: circle] } 

const centroid = require('@turf/centroid)
console.log(centroid)
// [Function] 
```

minor inconvenience but it would be nice to have it consistent

**Comment by mfedderly** [comment]
The modules that have these "extra" wrapper objects are exposing the fact that part of our modules are written in Typescript, while some are still written in Javascript. @turf/circle is one of these Typescript modules, and this is what happens if you `export default function circle()` in Typescript.

It turns out that you can emulate the behavior of centroid by using `export = circle;` in Typescript, but this has several drawbacks. I think that the best approach moving forward is to change everything to be a named export, so you would consume @turf/circle like so:

```
const {circle} = require("@turf/circle");
```

This gives us a way of consistently exporting things across our packages, and gives us the space we need in order to also export named types that can be helpful in the packages that support them. This is a breaking change, so for the 6.x branch I think the best option we can go with is to clearly document which packages require the .default lookups. We can then queue up the work to standardize this for a future major release.

Thoughts?
