### ISSUE TITLE
Current Status & Contributing

### ISSUE THREAD

**Issue by adamochayon** [Turfjs/turf#1981]
Hey @rowanwins, @DenisCarriere, @mfedderly and team!

I use the different turf utilities quite a bit and appreciate the great work you do on writing and maintaining the codebase.

I have a couple of questions relating to the current status and direction of turf:
- I have noticed that most of the latest stable releases are v5, some are v6, and all were last released about 3 years ago. However I have also noticed that some alpha versions were released recently.
What is the current status / goal as far as v5 / v6 (/ v7? I saw there is a long running PR for that as well)? What is the roadmap as it currently stands?
- The [contributing](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md) page is similarly pretty stale. How would you advise new contributors to join and help out? Where can we find a list of known bugs / features etc.

I would love to get more involved and help where I can to solve existing issues and help keeping this project going 💪🏽

**Comment by mfedderly** [comment]
Welcome!

@rowanwins and I have been the most active contributors recently, but we'd love to have some more friends.

As you have noticed, I've been releasing the 6.2.0 branch in alpha versions as I try to just get everything moving again. I arrived to this project after a few years of change and so I'm trying to just standardize everything, fix obvious build issues, etc. My biggest concern for 6.2.0 is trying to not break anyone's code.

I plan on doing mostly standardization and build system work in the near term. I would love for releases to become automatic. I also have an interest in getting Typescript's strictest checks turned on and getting eslint enforcing more things.

For V7, I think things got to the point where it was really hard to reason about that branch, and progress slowed down. There are a lot of improvements that came out of that work that @rowanwins knows about that I'm hoping to bring to the 6.x branch once we're finally able to release consistently again.

If you have specific Turf projects that you were already interested in working on, that would be a good a place to start as any. Otherwise you can look through the outstanding issues and pull requests to see if any are still relevant. All of the pull requests will need work at this point because I recently formatted the codebase with prettier. If turning on eslint/typescript rules one-by-one is something that's interesting to you I'd love help there as well.

**Comment by adamochayon** [comment]
Sounds excellent :)

The main friction points I have had recently are mismatches between versions - i.e. the fact that some packages latest is v5 where some are on v6. This has caused duplicate dependencies and inconsistencies in the past. An example I recently encountered is: `@turf/unkink-polygon` latest is `v5.1.5` and depends on `rbush v2` where `@turf/convex` latest is `v6.0.3` and it has brings in `concaveman` v1.2.0 as a dependency which in turn brings in `rbush v3`.

I have a feeling like the majority of these types of problems will get solved once the next stable lands, so I would be happy to assist in whatever is needed to get `v6.2.0` out the door.

Otherwise, there are many places where I have felt the typescript definitions are lacking (not strict enough / not accurate). There have been several issues opened on this subject in the past, and specifically related to using the existing [geojson definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/geojson/index.d.ts) (#1782, #1297, #1658) so this could be another point I can attempt to pick up if no one else is working on it.

**Comment by mfedderly** [comment]
If you want to give 6.2.0-alpha.3 a try and let us know if there's any glaring mismatches left that would be awesome.

I have also noticed the geojson typings being weird. I think the fix for that is going to have to wait for a little while because it would definitely be a breaking change. I think what we'll wind up doing is using the external version of the geojson types and removing our own copy of them.

Its probably worth creating a milestone for the breaking changes we want to make and doing them all in one go.

**Comment by adamochayon** [comment]
Yup that will probably be a breaking change, but hopefully one that will be relatively easy to swallow.
I also definitely agree that a milestone is good idea (but we also don't want another huge v7 branch to get out of control).

What are the changes in `v6.2.0` that make it an "alpha" currently? Are there any changes that you consider unstable?

**Comment by mfedderly** [comment]
Yeah but its quite a bit less lift to organize tickets into milestones than it is to have two concurrent branches. I'd like to just get a handful of releases out the door just fixing known issues before making the breaking changes.

I'm only really considering 6.2.0 unstable just because it hasn't been released in a long time and there's a few more things I want to make sure we get right before having everyone try to consume it. I'd hate to make it live and break a bunch of people's code. I went through and did as much as I could to standardize the builds and keep the package versions consistent which exposed quite a few bugs.

**Comment by adamochayon** [comment]
Yeah, the standardization is critical to make the development process easier. Thank you again for taking the lead on it.

I think once you get that first release out it would be best to create those milestones and start cleaning up issues / merging PRs. Of course, I would love to assist.

**Comment by dyakovlev** [comment]
👋 happy to help as well

**Comment by mfedderly** [comment]
6.2.0 has been released! I'm happy to open new tickets or revive old ones. In the meanwhile I'm working on fixing any of the issues that pop up as people start upgrading to 6.2.0.
