### ISSUE TITLE
turf.isobands vs. turf.isolines

### ISSUE THREAD

**Issue by tapiamcclung** [Turfjs/turf#2035]
Please provide the following when reporting an issue:

- [x] Using version 6.3.0.

I have  a set of data points and I run a simple grid interpolation. From that, I generate isolines and isobands to add as mapbox layers as such:
```
let options = {gridType: 'points', property: 'value', units: 'kilometers', weight: 2},
    grid = turf.interpolate(stations, 1, options),
    breaks = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
    lines = turf.isolines(grid, breaks, {zProperty: 'value'}),
    bands = turf.isobands(grid, breaks, {zProperty: 'value'}]});
```

The returned isolines are something like
```
{
  "type": "Feature",
  "properties": {
    "value": 4
  },
  "geometry": {
    "type": "MultiLineString",
    "coordinates": [ ... ]
  }
}
```
but the isobands are 
```
{
  "type": "Feature",
  "properties": {
    "value": "2-4"
  },
  "geometry": {
    "type": "MultiPolygon",
    "coordinates": [ ... ]
  }
}
```

Note that `value` for isolines is the associated value fo the break number (4), but it is a break range ("2-4") for the isobands.
Is this the expected behavior? I would like to use the same flow to add both layers to a mapbox map and want to avoid writing two different pant styles if possible. Cannot use a fill layer with interpolation on the 'fill-color' property if it is non-numeric.

Is there a way to return the numeric value for isobands?

Thanks!

**Comment by stebogit** [comment]
@tapiamcclung this is the expected behaviour, since the isolines represent `MultiLineString`s that connect points with the same `zProperty ` value, while isobands returns `MultiPolygon`s enclosing the regions containing points with `zProperty ` value between the correspondent `breaks` range.

Now for you case you should be able to use the same flow to process the returned GeoJSON objects by using 
```js
const value = Number(properties.value.split('-')[0]);
``` 
which should return the same value for both isolines and isobands.

**Comment by tapiamcclung** [comment]
Thanks!
