### ISSUE TITLE
@turf/rhumb-distance mutates its argument

### ISSUE THREAD

**Issue by diachedelic** [Turfjs/turf#2043]
I would expect it to behave like the other pure functions, but it [modifies the coordinate of the point passed to it](https://github.com/Turfjs/turf/blob/41a123a0e151be6a7e312dfecb91b69c4ff3f3f2/packages/turf-rhumb-distance/index.ts#L39). This seems like an accident!

**Comment by stebogit** [comment]
@diachedelic I'd argue that the issue is that [`@turf/invariant.getCoord`](https://github.com/Turfjs/turf/blob/41a123a0e151be6a7e312dfecb91b69c4ff3f3f2/packages/turf-invariant/index.ts#L22) does not return a copy of the coordinates but a reference to it, which propagates the issue into `@turf/rhumb-distance` and probably other packages.
@rowanwins @mfedderly what do you think?

**Comment by mfedderly** [comment]
There's two obvious options here:
1) change getCoord to return a `readonly number[]`
2) change getCoord to return a shallow clone

The end-result of approach 1 is maybe better, but it only helps people writing typescript and probably isn't meaningfully faster than just doing 2 and doing a clone on the way out. I worry about this same thing happening with getCoords though, I'd be less comfortable cloning something that has more than 2-3 entries.
