### ISSUE TITLE
Push new version to npm

### ISSUE THREAD

**Issue by daniel-marcus** [Turfjs/turf#2052]
Unfortunately, I can't `npm install @turf/turf` anymore due to the deprecated topojson dependency (solved in #2037).

Can you make the updated package available on npm?

Thanks in advance!

**Comment by azuddin** [comment]
same here. got error showing

> npm WARN deprecated topojson@3.0.2: Use topojson-client, topojson-server or topojson-simplify directly.

**Comment by M3kH** [comment]
I also have the same issue!

**Comment by antonioallen** [comment]
Ditto, same here.

**Comment by autarc** [comment]
As there are also some other small fixes already merged since [the last 6.3.0 update in January](https://github.com/Turfjs/turf/blob/master/CHANGELOG.md#630) (e.g. 402716a29f6ae16bf3d0220e213e5380cc5a50c4 which resolves a missing type import that currently forces TypeScript projects to enable `skipLibCheck`) it would be great if a new minor or fix release could be done. [While there are instructions](https://github.com/Turfjs/turf/blob/master/RELEASING.md) it doesn't seem to be automated so not sure whats the best approach here. Perhaps @rowanwins, @mfedderly or an other contributor could trigger it. Thanks in advance 🙂

**Comment by kylerchin** [comment]
Can we please merge this please?

**Comment by soltysaleksandr** [comment]
same issue only with npm v7+
any workarounds?

**Comment by daniel-marcus** [comment]
@soltysaleksandr you can install and import the needed functions as separate modules like

```
npm install @turf/union @turf/nearest-point
```

That worked for me.

**Comment by markusand** [comment]
This problem seems to be breaking quite an important number of projects (mines included) with people updating their systems. I think it deserves at least a patch update to npm.

**Comment by shaljam** [comment]
For now you can install `topojson-client`, `topojson-server` and `topojson-simplify` manually.
`npm install --save topojson-client topojson-server topojson-simplify`

**Comment by rowanwins** [comment]
v6.4.0 is now released, thanks for your patience
