### ISSUE TITLE
turf.{point,polygon,linestring} API confusion

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#207]
Turf has a few geometry helpers:

* turf.point
* turf.polygon
* turf.linestring

These have caused quite a bit of confusion, leading to questions like:

* how do i convert geojson points to turf points?
* does turf.point add a point to my map?

These are based on the more core misconceptions:

* turf.point produces something other than a geojson point
* turf function expect the output of helper functions, not geojson
* turf is integrated with mapbox.js or leaflet in some particular way

We have two routes of fixing this issue

* stronger documentation
* renaming or removing the helper functions

---

Personally, I lean towards the latter two: we should remove the helper functions from turf's api surface entirely and only use them internally. There should be _one true way_ of interacting with turf, and geojson primitives is it.

The path for implementing this would be to release turf versions with the functions exposed but with console.warns for a month or more, and then release turf 2.0.0 with them removed.

If we were to rename them, potentially calling them something like `turf.createPoint` or `turf.geometry.point` would reduce the pattern recognition between this and similar Leaflet or Mapbox.js functions.

---

The documentation path would be focused on laying this out as a very early concept and reiterating it often. I think this is what @morganherlocker  currently supports, and it does have the advantages that

* examples can be more concise
* turf helpers can do some useful validation of data
* we use turf helpers internally

My minor counterpoint is:

* i think geojson validation should happen at the function level, not the shortcut level
* and i'm comfortable with some turf modules, like `turf.meta` being internal-only.

/cc @Turfjs/owners

**Comment by lyzidiamond** [comment]
For sake of clarity, I think our examples should shift towards using geojson primitives. It will make our examples more verbose, which is a bummer, but it's likely closer to the experience of the average turf user and will alleviate confusion, as @tmcw describes above.

**Comment by mourner** [comment]
I'm in favor of keeping methods/names but better documentation + don't rely on these methods in examples as Lyzi suggests. Removing is not a good option since it's very useful not only to process existing GeoJSON but to generate it in scripts as well.

**Comment by tmcw** [comment]
> Removing is not a good option since it's very useful not only to process existing GeoJSON but to generate it in scripts as well.

Can you be a little more specific? These functions generally shorten something like `{type:'Point',coordinates:[0,0]}` to `turf.point([0,0])`: a savings of a few chars, not really a change in function.

**Comment by jseppi** [comment]
I'm in favor of removing the helpers from the public api. I don't think
most users will be creating geojson, but rather consuming it from other
sources.

**Comment by morganherlocker** [comment]
I personally find these helpers **extremely useful** almost every time I use Turf. That said I am also, *quite obviously*, extremely biased. 

I hate the idea of taking away useful features purely because people are not reading (this entire issue is clearly explained on the [first page of the docs](http://turfjs.org/static/docs/)). This strikes me as paternalistic, and I believe it sells our new users users short, while lessening utility. This is not meant as a dig at anyone other than myself, who has failed to convey how Turf is meant to be used. I still believe we can educate are way out of this.

I propose a multi-stage approach:

1. change all examples to use raw geojson
2. add a giant disclaimer on each of the geometry modules describing the usage
3. move the geometry modules to the end of the api docs
4. remove docs related to geometry, but keep them accessible 
5. move the geometry modules into their own separate npm module

Each of these steps provides stronger and stronger hints, and we can implement them incrementally until we hit a sweet spot. Each step makes it more difficult for advanced users to dive in, but they need much less help, so we have wiggle room.

Turf is meant to work for a lot of different types of users. It **has** to work for people building geospatial analysis algorithms (why I built Turf in the first place), but it also needs to accommodate new users with less time to devote to programming and documentation. I'm confident we can find a middle ground here if we take this slowly, but deliberately. If not, then I'm fine with moving these to their own module too.

**Comment by tmcw** [comment]
Okay, let's start with the first task and try to get it shipped next week:

* [ ] Remove turf.{point,polygon,featurecollection,linestring,feature} from all examples

**Comment by mourner** [comment]
> savings of a few chars

Just a few chars can make a _huge_ difference when it comes to APIs like that. @morganherlocker :+1: fully agree, great plan.

**Comment by lyzidiamond** [comment]
^ I can take that on, @tmcw

**Comment by lyzidiamond** [comment]
Also, related, I'm putting together a ticket about the responses I got to the turf exercise. Some excellent feedback that may feed our thinking here.

**Comment by lyzidiamond** [comment]
I have removed turf.{point, polygon, featurecollection, linestring} from all examples except the following:

- [turf-intersect](/turfjs/turf-intersect) because the example is still throwing an `undefined is not a function` error

I kept turf-random and turf-sample in the examples that used them. I also kept the existing examples for the helper and data functions.

**Comment by lyzidiamond** [comment]
Just deployed new examples to live site!

**Comment by morganherlocker** [comment]
I have noticed a substantial decrease in confusion since the examples were changed and we put the data section front and center. I think we have covered both 1) people reading the docs and 2) people making copy pasta :spaghetti: 

Closing, but can revisit if we need to.
