### ISSUE TITLE
Shared geojson fixtures

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#208]
We have a lot of modules that have the need for test fixtures. I think we should have one module of reusable fixtures. Here's one I made a while back: https://github.com/mapbox/geojson-fixtures

Also: we should make sure that `.npmignore` ignores `test` so that fixture outputs are not added into npm package downloads.

**Comment by tmcw** [comment]
Add to this: geojsonhint on all outputs.

**Comment by tmcw** [comment]
:+1: done, first module to hit was turf-centroid https://github.com/Turfjs/turf-centroid/blob/master/test.js 

Module that encapsulates magic is geojson-fixtures: https://github.com/mapbox/geojson-fixtures#geojson-fixtures - this does

* `UPDATE=true npm test` to update fixtures
* Runs geojsonhint on outputs
* Ensures output is as desired.

**Comment by morganherlocker** [comment]
> we should make sure that .npmignore ignores test so that fixture outputs are not added into npm package downloads.

:+1:

> I think we should have one module of reusable fixtures.

yes, I have built some of these too. I think this will work as a baseline for verifying general "kick the tires" level testing. At the same time, I do think custom fixtures per module are extremely important for testing edge cases or algorithm specific gotchas. I think this should be provided **in addition to** current tests, rather than replacing current tests.

**Comment by tmcw** [comment]
>  At the same time, I do think custom fixtures per module are extremely important for testing edge cases or algorithm specific gotchas. I think this should be provided in addition to current tests, rather than replacing current tests.

Yep, agree

**Comment by tmcw** [comment]
Modules that can, now use geojson-fixtures.
