### ISSUE TITLE
Union operation a bit off

### ISSUE THREAD

**Issue by behatted** [Turfjs/turf#2082]
Hi,

First of all thanks for the great work. Second, I may well be missing something, or not understanding something, but when I try to use the union operation, the resulting polygon seems quite different from the originals.
Using turf 6.3.0, when I use this code:

```
const poly1 = turf.polygon([[[-97,58],[-110,43],[-79,43],[-97,58]]])
const poly2 = turf.polygon([[[-72,54],[-97,37],[-51,37],[-72,54]]])
const misalignedUnion = turf.union(poly1, poly2)
```

Link here:
https://jsfiddle.net/Murgian/uyjzfgd5/3/

And a MultiPolygon showing the two originals and the combined polygon here:
https://github.com/behatted/TurfUnion/blob/main/TurfUnion.geojson

Is this normal? Or am I doing something wrong?

Thanks!

**Comment by rowanwins** [comment]
Hi @behatted 

This is somewhat of an issue upstream in the [`polygon-clipping` library,](https://github.com/mfogel/polygon-clipping/) but I'd hazard a guess that it's basically because your lines are covering such a large distance and so it's having a hard problem calculating an accurate intersection point.

Not a particularly helpful answer sorry

**Comment by behatted** [comment]
Sorry for the incredibly late reply! It seems a shame that polygon clipping cannot deal with larger areas, but there we go. Thanks for the response.
