### ISSUE TITLE
there is one error of lineOffset。

### ISSUE THREAD

**Issue by Tompythonorange** [Turfjs/turf#2086]
- [ "@turf/turf": "^5.1.6",] 
//that.lineArr type is right
 let linePY = turf.lineString(that.lineArr);

//that.offsetDistance = 20m
var offsetLine = turf.lineOffset(linePY, that.offsetDistance, {
  units: "meters",
});

//the true is the distance only aboult 16m，when I change unit，is the same wrong, there is no loss of precision in intermediate data

**Comment by matkoniecz** [comment]
Maybe more experienced people understand this, but it is unclear to me what is supposed to be a problem.

Have you passed "20m" string as distance value?

**Comment by Tompythonorange** [comment]
I hope move 20m, but the result is only move about16.5m



At 2021-06-16 23:42:53, "Mateusz Konieczny" ***@***.***> wrote:

Maybe more experienced people understand this, but it is unclear to me what is supposed to be a problem.

Have you passed "20m" string as distance value?

**Comment by JamesLMilner** [comment]
Unfortunately I feel like this issue is unclear and as there are many bugs and issues filed against lineOffset, as such it probably makes sense to close this unless there is a reproducible test case with a clear explanation of what happened and what was expected. In the mean time please feel free to try the latest version, 6.4 and see if that resolves your issue.
