### ISSUE TITLE
Features or Geometries: decide

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#209]
For instance:

* turf-line-distance takes a feature with a linestring geometry or a linestring geometry
* turf-distance takes two features with point geometries (but is incorrectly documented)

Which should it be: geometries, features, or auto-unwrapping? We should make this decision and aim for uniformity.

**Comment by morganherlocker** [comment]
Features have been the default to date, with geometry unwraps supported inconsistently.

Many functions require Features, since they work with properties. I think we should always accept Features at a minimum. After that consistently unwrapping geometry where possible makes sense, but I could take it or leave it. 

I think this distinction led to my confusion when jsdocing a few of the modules. In writing `@param {Point} from origin point` I had assumed this would mean "a GeoJSON Point Feature".

**Comment by lyzidiamond** [comment]
Apologies for any incorrect documentation! I didn't realize that some functions took straight up geometries. For ease of user understanding, I'd vote for every function to take Features and do internal unwrapping (assuming I'm understanding the question correctly).

**Comment by tchannel** [comment]
@lyzidiamond I would recommend we allow either/or, excepting modules that rely specifically on features/properties existing (such as most of aggregation modules).

This is the intent of turfjs/turf-to-features and turfjs/turf-to-geometries - to provide a uniform way for our modules to wrap / unwrap as needed

**Comment by lyzidiamond** [comment]
@tchannel The doc has been updated significantly since this ticket. All of the examples use geojson primitives that have an empty object for properties and (unless I'm way off base) there are many tests that require `properties` even with a blank object as a value, even when the properties aren't required by the function.

Is that right @morganherlocker @tmcw or am I way off base?

**Comment by morganherlocker** [comment]
How about only documenting support for features, but backfilling geometries as we go? I would *like* to support both eventually for both performance and usability reasons where possible, but I don't want to pinky-swear it yet. Sound reasonable?

**Comment by tchannel** [comment]
:+1: from me

**Comment by tmcw** [comment]
All modules that used to take Features with Point Geometry objects inside now support both, transparently, in turf 3
