### ISSUE TITLE
@turf/distance doesn't consider altitude

### ISSUE THREAD

**Issue by IPWright83** [Turfjs/turf#2143]
This affects the latest version as of 6.4.0

It's difficult for me to provide an example as it's buried within a library I'm trying to modify, but essentially I've discovered that using @turf/distance to calculate the distance between two points that vary only in altitude results in a value of 0, which is incorrect.

Looking at https://github.com/Turfjs/turf/blob/master/packages/turf-distance/index.ts#L42 is takes no account of the altitude in calculations :(

**Comment by JamesLMilner** [comment]
Hi @IPWright83, you're right that distance does not take into account altitude (see the docs: https://turfjs.org/docs/#distance). Although Positions have an optional parameter in the GeoJSON spec, it is not supported in distance calculations. I'm not sure I agree this is incorrect/is a bug as it matches the specification of the function which is measuring the distance between two latitude/longitude pairs. Even if we wanted to support altitudes, the underlying formula, the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula), doesn't support altitude calculations.

**Comment by stebogit** [comment]
I agree with @JamesLMilner , I don't think this is an error or bug. GeoJSON specs do allow a third optional position/coordinate element, however the specs clearly refers to planar features, somewhere described as parallel to the [Geoid](https://en.wikipedia.org/wiki/Geoid?wprov=sfla1) (curved) plain. No elevation features are considered in the Geoid by design.
In fact, [the specs](https://datatracker.ietf.org/doc/html/rfc7946#section-1) defines 7 geometries up to 2D region of space (no volume for them is ever considered or implied).
