### ISSUE TITLE
es6 import of turf fails with Uncaught TypeError

### ISSUE THREAD

**Issue by backspaces** [Turfjs/turf#2144]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.

6.2.0, 6.3.0, 6.5.0: Just use comments to choose which version to use.

Note: this is a recent failure. It worked fine a few months ago. It also fails with an npm install of turf.

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).

Not applicable

- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Running this:
```
<!DOCTYPE html>
<html>
    <head>
        <title>Bug</title>
    </head>
    <body>
        <script type="module">
            // import * as turf from 'https://unpkg.com/@turf/turf@6.2.0/dist/es/index.js'
            // import * as turf from 'https://unpkg.com/@turf/turf@6.3.0/dist/es/index.js'
            import * as turf from 'https://unpkg.com/@turf/turf@6.5.0/dist/es/index.js'
        </script>
    </body>
</html>
```
Produces:
```
Uncaught TypeError: Failed to resolve module specifier "@turf/isolines". Relative references must start with either "/", "./", or "../".
```

Apparently bare module specifiers are used which are not legal imports. Ex: isolines uses:
```
import bbox from '@turf/bbox';
import { featureEach, coordEach } from '@turf/meta';
import { collectionOf, getCoords } from '@turf/invariant';
import { isObject, featureCollection, multiLineString } from '@turf/helpers';
import objectAssign from 'object-assign';
```

**Comment by JamesLMilner** [comment]
This looks like a legitimate issue to me. Probably an easy fix? Maybe there's a eslint rule that disables this cc @rowanwins @mfedderly

**Comment by backspaces** [comment]
Yay! Thanks for the quick response!

**Comment by JamesLMilner** [comment]
@backspaces apologies, thinking about this a bit more, the issue here is that the bare module specifiers are required because turf is modular, and those packages are installed separately when you use turf as individual packages. I.e. `@turf/invariant` will be a modular dependency for `@turf/isolines`.

As such this is somewhat expected behaviour as the browser can't map the bare module specifiers to `node_modules` (or anywhere for that matter) in the browser (although there is some interesting movement on this with [import maps](https://blog.logrocket.com/es-modules-in-browsers-with-import-maps/). In reality this is how most ES6 libraries that have external dependencies would operate in the browser.

Your options really are:

1) Use ES5 version from the CDN:

```html
<script src="https://unpkg.com/browse/@turf/turf@6.3.0/"></script>
<script>console.log(turf)</script>
```

2) Use a bundler like Webpack, Rollup etc
