### ISSUE TITLE
turf.union not accepting unpacking: turf.union(...array)

### ISSUE THREAD

**Issue by icculp** [Turfjs/turf#2162]
Please provide the following when reporting an issue:

- [6.5.0 / 5.1.6 ] The version of Turf you are using, and any other relevant versions.
- [ ] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [ ] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

I built an app last year to take a long list of 655 parcel coordinates and plot them on a map. Rather than load each parcel as a separate layer, I used turf.union to merge the layers into one. This reduced overhead in the browser and solved the problem of overlapping layers changing colors. I used unpacking like buffers_merged = turf.union(...buffers), where buffers is just an array of polygon features. This worked just fine when I build it but my app stopped working a while back. After spending some time troubleshooting, discovering the 6.5.0 version on github seemed to only accept two inputs, I reverted to the version of turf that was older than when I built the app, which happened to be 5.1.6 and this solved my problem. Not sure why the newer versions stopped looping through args...
![image](https://user-images.githubusercontent.com/57159226/127715395-4c980d63-7c79-4277-a0ff-d4b6d1af7cd6.png)
![image](https://user-images.githubusercontent.com/57159226/127715407-39910bf1-f12d-4815-bc5e-d4469bd2cd46.png)

**Comment by JamesLMilner** [comment]
Union has taken two inputs since at least 2018 https://github.com/Turfjs/turf/commit/a371807f78364820f15ab8f9ee3dc5aba51b7bac#diff-ca6c0026b09f9758d1e9cfcfae0c204a03d1e5d8307a158c613087dc433f8f20. In honesty I'm not sure if it used to behave differently previously as the git history only goes back that far for that module directory, but the current API only accepts two polygon arguments and an options arg. 

You should be able to get the same behaviour by doing:

```typescript
let unioned = polygons[0];
for (let i = 1; i < polygons.length; i++) {
     unioned = turf.union(unioned, polygons[i]);
}
```

Hope that helps!

**Comment by icculp** [comment]
Hey James, thanks for the response. I see I pasted the same screen shot twice, I meant to paste the ss of the code from 2018 as you mentioned that looped through all args. I pointed my app to use 5.1.6 and got it to work, but I had considered using a loop like you suggested with the latest version.

**Comment by rowanwins** [comment]
I suggest we should reopen this @JamesLMilner as it's a pretty common requirement and Turf used to do it (I think the v5 series and prior used to accept unlimited arguments), I think we should consider how to tackle this for v7.

**Comment by JamesLMilner** [comment]
Sure thing, apologies if I closed too hastily. Happy to see how we could support it again if there's appetite.

**Comment by rowanwins** [comment]
For note - looping many through many features to perform union operations to handle something like a featurecollection is really slow compared to processing the full featurecollection in a single operation, this is because of how the underlying algorithm works which is constructing a sweepline made up of all the segments. I helped someone out on a case recently where they went from 1 minutes of processing (because they were using a loop) compared to 5 seconds (passing everything in a single go directly to `polygon-clipping`)

**Comment by mfedderly** [comment]
For similar reasons we would also like to update @turf/difference and @turf/intersect to take the same API.
