### ISSUE TITLE
Bug: Cloning date objects in turf-clone with turf-clusters-dbscan

### ISSUE THREAD

**Issue by flodaniel** [Turfjs/turf#2196]
Please provide the following when reporting an issue:

- [x] The version of Turf you are using, and any other relevant versions.
@turf/turf 6.5.0

- [x] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
https://gist.github.com/Firetrip/f16afbc98bf43ef569527321c28bcd66
- [x] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

Having points as input for clustersDbscan with the following format: 

```
turf.helpers.Feature<
            turf.helpers.Point,
            {
                userMatchRecommendation: UserMatchRecommendation;
            }
        > 
```

where UserMatchRecommendation (reduced version) is defined as: 

```
export class UserMatchRecommendation {
    username: String; 
    arrivalTime: Date; 
}
```

Results to the loosing the arrivalTime data object. The bug seems to occure not within the clustersDbscan function, but when cloning the properties. 
Using `mutate: true` when calling the clustersDbscan resolves the issue, but without it, the point features from the result look like in the gist file above, with an empty object for arrivalTime.

**Comment by JamesLMilner** [comment]
I think the problem is here that `turf/clone` doesn't have any special case for dates:

https://github.com/Turfjs/turf/blob/master/packages/turf-clone/index.ts#L89

It's just trying to copy the object as if it was a plain object. We could add a case for handling dates specifically like:

```typescript
else if (value instanceof Date) {
   cloned[key] = new Date(+value);
}
```

Probably an argument for a more robust cloning approach or using a third party library there because there's probably plenty of things that will fail there (Errors, Functions, Symbols, Maps, Sets etc)

**Comment by JamesLMilner** [comment]
Thinking about this a Date isn't a valid JSON type (`string`, `number`, `null`, `boolean`, `array`, `object`) -  the purpose of `turf/clone` is to clone GeoJSON objects which by definition also have to be valid JSON. As such I don't actually think this is a bug.

If you so require you could convert the dates number numbers (`+date`) and then store them that way (`A JavaScript date is fundamentally specified as the number of milliseconds that have elapsed since midnight on January 1, 1970, UTC` - MDN).
