### ISSUE TITLE
line-split splits line with point incorrectly

### ISSUE THREAD

**Issue by kriku** [Turfjs/turf#2206]
@turf/line-split v6.5.0

when I try split line in the middle point it's doesn't work, or works incorrectly:

for example:
```js
// DOESN'T SPLIT

const splitResult = lineSplit(
  lineString(
    [
      [-82.70117234189014, 27.807713078712464],
      [-82.68750911606274, 27.820249180132468],
      [-82.67224700210662, 27.807325340910207],
    ]
  ),
  point(
    [-82.68750911606274, 27.820249180132468],
  )
);

/*
splitResult = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -82.70117234189014,
            27.807713078712464
          ],
          [
            -82.68750911606274,
            27.820249180132468
          ],
          [
            -82.67224700210662,
            27.807325340910207
          ]
        ]
      }
    }
  ]
}
*/

// WRONG SEGMENTS

const splitResult = lineSplit(
  lineString(
    [
      [106.98947637756622, 47.99091756456802],
      [106.88883167471015, 47.90095512993095],
      [107.01310600345415, 47.774271059598235],
    ]
  ),
  point(
    [106.88883167471015, 47.90095512993095],
  )
);


/*
splitResult = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            106.98947637756622,
            47.99091756456802
          ],
          [
            106.88883167471015,
            47.90095512993095
          ],
          [
            106.8888317,
            47.9009551
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            106.8888317,
            47.9009551
          ],
          [
            107.01310600345415,
            47.774271059598235
          ]
        ]
      }
    }
  ]
}
*/
```

as the correct output I expect two segments of split line, 
with middle point coordinate in end of first and start of second part

**Comment by dpmcmlxxvi** [comment]
@kriku As for your two cases:

 - **DOESN'T SPLIT**:
   - It doesn't split because `@turf/line-split` truncates the splitter to a precision of 7 places but not input feature. According to several previous issues (e.g., #852) this was a compromise between keeping to the GeoJSON recommendation of not using too many decimals and still addressing several edge cases involving point splitters.
   - Also, the code uses `rbush` to find the feature the point splitter intersects. From what I can tell this will always be a problem as long as the splitter is truncated and `rbush` is used since truncating will move the point around and there will always be edge cases where the point ends up moving just off the target line and outside it's bounding box.
   - There two solutions.
     - For you in the short term. You can truncate the inputs to 7 places. This worked for me.
     - For turf in the long term. I think a more robust solution would be to check find if the splitter comes within a certain tolerance of the target feature and if it does then project the splitter onto the feature and use that as the splitter.
 - **WRONG SPLIT**:
   - I think the truncation issue is the culprit as well.

**Comment by kriku** [comment]
@dpmcmlxxvi thanks you!
