### ISSUE TITLE
booleanPointOnLine false positives

### ISSUE THREAD

**Issue by kriku** [Turfjs/turf#2240]
@turf/boolean-point-on-line 6.5.0

for all points on the second coordinate, for segment with length 0, function returns false positives.

```js
booleanPointOnLine([0, 0], [[0, 0], [0, 0]]);
// true
booleanPointOnLine([1, 0], [[0, 0], [0, 0]]);
// false
booleanPointOnLine([0, 1], [[0, 0], [0, 0]]);
// true - WRONG
booleanPointOnLine([0, -1], [[0, 0], [0, 0]]);
// true -WRONG
booleanPointOnLine([0, 0.2], [[0, 0], [0, 0]]);
// true - WRONG
booleanPointOnLine([1, 2], [[1, 1], [1, 1]]);
// true - WRONG
// ... etc
```

**Comment by JamesLMilner** [comment]
Thanks for raising. I'm not sure that `[[0, 0], [0, 0]]` or ``[[1,1], [1, 1]]` is a valid LineString, which kind of makes me think this is a explicitly uncovered case. That is to say, I'm not sure it's turfs place to validate every geometry thrown at each function. This being said, I wonder if we should do some basic checks to ensure these kind of cases return false?

**Comment by twelch** [comment]
I also think these two examples are not valid LineStrings because their two vertices are the same.

Should a basic check then walk through all the linestring vertices and make sure at least one is different than the others?  My two cents, seems like a job for a validation function (#64) and this ticket can be closed in favor of.

Why close?  I would suggest it's on the caller to validate beforehand as it could start to add up in cpu cycles?  And would you implement basic checks in every turf function then?  Seems unmanageable.

I just noticed that there is a still open ticket for a validation function (#64) and an undocumented/yet to be integrated `boolean-valid` function (#1302), which is available on npm.   But it doesn't validate to the level being discussed here - https://github.com/Turfjs/turf/blob/master/packages/turf-boolean-valid/index.ts#L38.  This seems like the place to focus effort, improve `boolean-valid` and get it published as a first class turf function.

This post I think demonstrates that Postgis behaves the same way, you can create invalid geometries, and its up to you to validate them, and the validation function will catch it - https://gis.stackexchange.com/questions/284733/why-can-postgis-create-linestring-from-the-same-values-of-coordinates-of-the-poi
