### ISSUE TITLE
Point grid via four corners & num. of rows and columns.

### ISSUE THREAD

**Issue by ontheway16** [Turfjs/turf#2320]
Hello, this is a feature request since this is the closest thing to what I need. I am trying to create a grid of points, based on four corner coords, and number of rows and columns, provided. The bounding box is not a rectangular one, therefore the distances between points are only equal within same row, or within same column. Unfortunately, I could not find any tool that can handle this.

**Comment by stebogit** [comment]
@ontheway16 there's no package to do that.
It gets tricky though to draw what you suggests if the corners end up being a rectangle for example: since the grid cell are square the grid will always be a square, which doesn't necessarily fit well in a rectangle. Same if the number of rows and columns don't match.
You can mask the grid so you only get the points that are inside it, however it gets very specific to your application, so I don't see this as material for a package.

Below some lines to give you an idea of the few components you might want to play with:
```js
const rows = 10
const cols = 6

const red = turf.point([-70.823364, -33.5], {'marker-color': 'red'})
const blue = turf.point([-70.473175, -33.302986], {'marker-color': 'blue'})
const extent = [...red.geometry.coordinates, ...blue.geometry.coordinates]

const mask = turf.bboxPolygon(extent)

const width = turf.rhumbDistance(red, turf.point([turf.getCoords(blue)[0], turf.getCoords(red)[1]]))
const height = turf.rhumbDistance(red, turf.point([turf.getCoords(red)[0], turf.getCoords(blue)[1]]))

const cellSide = Math.max(width, height) / Math.max(cols, rows)

const grid = turf.pointGrid(extent, cellSide, {mask})
```

![Screen Shot 2022-08-06 at 11 15 58 PM](https://user-images.githubusercontent.com/12717225/183277941-1e8be483-a041-4963-846f-96a25e2951f3.png)
