### ISSUE TITLE
Turf manifesto/guiding principles

### ISSUE THREAD

**Issue by rukku** [Turfjs/turf#233]
I'm just curious as I'm still trying to understand the project. I like it a lot but I'm a bit unsure as to what our final destination is. Is our objective to implement a GIS in javascript? Or something new altogether?

**Comment by morganherlocker** [comment]
Turf is a geospatial analysis engine. Its purpose is to provide the pieces people need to understand and manipulate geographic statistical data. It does this while focussing on:

1. **freedom** and modularity: no lock-in to a vendor **or** a workflow/mindset, parts are interchangeable
2. **usability**: clear docs and sensible APIs
3. **power**: maximal performance and flexibility

> Is our objective to implement a GIS in javascript?

"GIS" is not a particularly helpful term, since it often means different things to different people. In a very real sense though, Turf (and the surrounding js tool system) already is a fully implemented GIS. You can already build GIS applications from front to back in javascript.

> I'm a bit unsure as to what our final destination is.

Turf has mostly already realized its goal of providing a low level programatic interface for geospatial analysis. The main goals remaining are:

- better tests
- more usable APIs where necessary
- more educational tools
- better performance
- smaller footprint
- additional features/algorithms as needed

Turf is already pretty different from its predecessors. I expect that future paradigm shifting will take place on top of Turf, rather than inside of it (eg: GUIs, streaming data, declaritive processing, mapreducing algorithms, combinatorial learning algorithms, etc.). Turf is explicit in allowing these use cases, but not forcing them on users. I would bet that at least one of those will enable entire new workflows for processing geo-data over the next couple years.

**Comment by rukku** [comment]
>Turf is a geospatial analysis engine. Its purpose is to provide the pieces people need to understand and manipulate geographic statistical data. 

>Turf has mostly already realized its goal of providing a low level programatic interface for geospatial analysis.

Thanks @morganherlocker! I think I understand it better now. Do we have a roadmap? I'm curious Turf will support rasters in the future.

**Comment by tchannel** [comment]
@rukku I don't know about everybody else, but I personally think that providing some form of raster support could be a really interesting addition down the line

@morganherlocker thanks for that summary, really helpful
