### ISSUE TITLE
@turf/dissolve converts integer feature id to string

### ISSUE THREAD

**Issue by stonetip** [Turfjs/turf#2389]
Using https://www.unpkg.com/@turf/turf@6.5.0/turf.min.js, the resulting polygon from turf.dissolve has its **id** value converted to a string, although the input value for each source polygon was an integer.

This causes issues for filtering data.

**Comment by JamesLMilner** [comment]
Hey @stonetip thanks for raising this. Firstly, can you provide a code snippet and example input that you are using here? This makes it easier to investigate.

On the surface, it is hard to say exactly what `dissolve` should do with regards to the `id` of the resulting Polygon. I think as a minimum it should probably be documented, but it's hard to say what the resulting polygon `id` should be as the input ids can be arbitrary and it's impossible to cover every case. It is relatively straight forward to give the resulting polygon any id you so wish, so this problem is probably better solved in the end developer space.

**Comment by rowanwins** [comment]
In version 7 (currently published as an alpha) the dissolve operation will discard the feature id. As James said the right behaviour here is probably tricky to determine, but at least it's now not wrong.

https://runkit.com/rowanwins/6450d8c17d561300083cc27f

**Comment by stonetip** [comment]
In light of the comments above, I don't disagree with the decision to do away with an ID altogether. That seems to be the customary behavior in desktop GIS applications, at any rate! After I review my code, I will probably make a pull request to update the documentation for [http://turfjs.org/docs/#dissolve](http://turfjs.org/docs/#dissolve) (something along the lines that when a dissolve occurs, it is stripped of properties, including any ID). I know in our code, we rely on the resulting features having an ID for highlighting on mouseovers, etc.
