### ISSUE TITLE
@turf/bbox import issue turf 6.5.0

### ISSUE THREAD

**Issue by michaelfaith84** [Turfjs/turf#2394]
Default import is broken.

As noted with bbox-polygon previously, after importing to use it you must invoke via bbox.default().

**Comment by ashley-mort** [comment]
I get a similar problem if I make a custom build (and import with RequireJS).  I have to do like turf.area.default instead of turf.area and turf.helpers.polygon instead of turf.polygon.

What am I doing wrong?  I don't have this problem using a CDN version like: https://cdn.jsdelivr.net/npm/@turf/turf@6/turf.min.js

All I really wanted was to add and use the rectangle-grid package.

npm install @turf/area @turf/bbox @turf/difference @turf/helpers @turf/meta @turf/rectangle-grid
npm install -g browserify
npm install -g uglify-js
browserify main.js -s turf | uglifyjs > outTurf-min.js
browserify main.js -s turf > outTurf.js

**main.js**
module.exports = {
    area: require('@turf/area'),
    difference: require('@turf/difference'),
    helpers: require('@turf/helpers'),
    meta: require('@turf/meta'),
    rectangleGrid: require('@turf/rectangle-grid')
};
