### ISSUE TITLE
New module @turf/interpolate

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf#24]
Takes a set of points and estimates values on a grid.

**Comment by stebogit** [comment]
@DenisCarriere this seems a lot similar to the "validation" step we tried to add inside `isobands` (random points to grid).
In order to reduce the complexity of that module, which should only do one thing, what if I implement this one and we keep the input of `isobands` (and `isolines`) as `pointGrid`, since this module will be available?

**Comment by DenisCarriere** [comment]
👍 @stebogit Sounds like a good idea.

Many of the "complex" modules usually have 3-4 modules that can be discovered/created prior to making the main module (ex: `isobands` in this case).

**Comment by stebogit** [comment]
Just to make sure we are on the same page about what this module should do.
My understanding is, based for example on `isobands` and `isolines` input requirement, to take any set of points with an `elevation`/`z` value and transpose them to a `pointGrid`, interpolating said "vertical" value on the grid.
Is that correct @morganherlocker and @DenisCarriere ?

**Comment by DenisCarriere** [comment]
👍 Sounds right to me.

**Comment by stebogit** [comment]
Implemented with #832
