### ISSUE TITLE
shortest-path: Multiple obstacles are ignored

### ISSUE THREAD

**Issue by tspoke** [Turfjs/turf#2425]
Hi, I'm having an issue with using multiple obstacles with shortest-path.

- Using latest version of turf
- ShortestPath only consider the first polygon to find the path when using a list of obstacles.

------- 

Example : 

<img width="286" alt="normal" src="https://user-images.githubusercontent.com/7793586/230331031-80cabd75-215a-4a80-b139-8a4b48473d5c.png">

Reversing array and running again : 

<img width="259" alt="reversed" src="https://user-images.githubusercontent.com/7793586/230331054-3a8796e4-57e0-4d08-a4f2-bca8ce961539.png">

-----------

JSfiddle below, uncomment the commented line to see the change of the two paths.

https://jsfiddle.net/c2vsLe4u/19/

**Comment by tspoke** [comment]
When passing a Polygon with multiple nested array, the shortest-path create a FeatureCollection with it : https://github.com/Turfjs/turf/blob/v6.5.0/packages/turf-shortest-path/index.js#L72

To make it work I had to create myself the feature collection instead of sending a Polygon : 

```
const featureCollection = turf.featureCollection([]);
obstacles.forEach(obstacle => featureCollection.features.push(turf.polygon([obstacle])))

// use the feature collection instead of the Polygon
const path = turf.shortestPath(pointA, pointB, {
    obstacles: featureCollection,
    units: "meters",
    resolution: 25
  });
```

See the updated jsfiddle here : https://jsfiddle.net/168Lbt7s/1/

IMO the library should be able to detect multiple polygons and create the appropriate FeatureCollection if needed.

**Comment by twelch** [comment]
@tspoke glad you found a way forward.  Note that a polygon is more than its outer boundary.  It's one or more linear rings, where the first ring is the exterior ring or outer boundary of your polygon, and every ring after that is a hole in the polygon.

See https://www.rfc-editor.org/rfc/rfc7946#appendix-A.3

From looking at your example `obstacles` array, I think you might be creating a single polygon with a hole, instead of an array of two polygons as you think.  I think you just need another level of array nesting to get your array of two polygons.  But as you saw, FeatureCollections are the way Turf works with arrays of features.  Here's the signature for the obstacles parameter.

```
obstacles?: Polygon | Feature<Polygon> | FeatureCollection<Polygon>;
```

**Comment by rowanwins** [comment]
@tspoke you might also want to look into my [visibility-graph library](https://github.com/rowanwins/visibility-graph) . We are considering deprecating the shortest-path module in TurfJS as it's implementation isn't ideal as it's doing a rasterisation of the vector geometries.

**Comment by tspoke** [comment]
@rowanwins I just tested and integrated your visibility-graph lib ! It works nicely and I dropped the shortest-path in favor of your implementation (which is much faster). When do you plan to integrate it in turf ? If not, can you publish it on npm ?

FYI, I upgraded and modified the dependencies to compile as a module and not a commonjs with rollup.

Thanks for your work !

**Comment by rowanwins** [comment]
Hey @tspoke

I'm glad it's fitting the need. The module is already available on [npm already here](https://www.npmjs.com/package/visibility-graph.js). It probably won't make it into Turf because it doesn't really fit neatly with how most Turf modules work (eg it's class-based and only loosely related to geojson).
If you want to put up a PR in the repo for those adjustments feel free and I'll try and get around to merging it in and re-releasing :)

Cheers
