### ISSUE TITLE
Should togeometries and tofeatures clone before modifying / returning?

### ISSUE THREAD

**Issue by tchannel** [Turfjs/turf#248]
It could make immutability throughout turf simpler -- as we move towards supporting both geometries and features, we're likely to use Turfjs/turf-to-geometries and Turfjs/turf-to-features more often.

**Comment by tmcw** [comment]
Kind of for this reason, I feel like the [turf-meta](https://github.com/Turfjs/turf-meta) approach of providing iterators instead of doing transformations makes sense, because you can let users do their own immutable-style calculations, or if they're just using the code to do something like comparisons or `.reduce`, there's no cost of a clone

**Comment by tchannel** [comment]
@tmcw thanks for the feedback. Maybe I'll take a crack at building some stuff using the meta approach and see if that's reasonable enough for me to ditch the tofeatures / togeometries approach. I do like the idea that we could reduce memory footprint by avoiding copies, especially for modules that only need to iterate over an object, not modify it
