### ISSUE TITLE
spatial join of polygon to polygons

### ISSUE THREAD

**Issue by timiyay** [Turfjs/turf#295]
I have a use case where I'd like to use turf to perform spatial joins between a master polygon, and another set of polygons.

The end result would be the master polygon, with the joined `properties` of the other polygons. Where the polygons have different attribute values, these would be concatenated into an array.

Does anyone else think this use case would be a useful to have in turf? Or should I just make my own library for this?

Example:

```js
var master = {
  "type": "Feature",
  "properties": {
    "fill": "#0f0",
    "id": 1,
    "area_type": "A"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-122.801742, 45.48565],
      [-122.801742, 45.60491],
      [-122.584762, 45.60491],
      [-122.584762, 45.48565],
      [-122.801742, 45.48565]
    ]]
  }
};


var poly1 = {
  "type": "Feature",
  "properties": {
    "fill": "#0f0",
    "id": 2,
    "area_type": "B"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-122.801742, 45.48565],
      [-122.801742, 45.60491],
      [-122.584762, 45.60491],
      [-122.584762, 45.48565],
      [-122.801742, 45.48565]
    ]]
  }
};

var poly2 = {
  "type": "Feature",
  "properties": {
    "fill": "#00f",
    "id": 3,
    "area_type": "C"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [[
      [-122.520217, 45.535693],
      [-122.64038, 45.553967],
      [-122.720031, 45.526554],
      [-122.669906, 45.507309],
      [-122.723464, 45.446643],
      [-122.532577, 45.408574],
      [-122.487258, 45.477466],
      [-122.520217, 45.535693]
    ]]
  }
};

var joined = turf.tag(master, [poly1, poly2]);

console.log(joined);

// {
//   "type": "Feature",
//   "properties": {
//     "fill": "#0f0",
//     "id": [1, 2, 3],
//     "area_type": ["A", "B", "C"]
//   },
//   "geometry": {
//     "type": "Polygon",
//     "coordinates": [[
//       [-122.801742, 45.48565],
//       [-122.801742, 45.60491],
//       [-122.584762, 45.60491],
//       [-122.584762, 45.48565],
//       [-122.801742, 45.48565]
//     ]]
//   }
// };
```

**Comment by rowanwins** [comment]
Gday @timiyay 

This certainly sounds like it could be a handy module. I've got a module for getting [overlapping polygons](https://github.com/rowanwins/turf-overlap) (note it's still in dev and not really part of turf yet but hopefully one day :)  ) which could probably be adapted relatively easily.

If you're happy to have a shot I'll leave it with you otherwise I could possibly take a look in the next week some time.

Cheers
Rowan

**Comment by tcql** [comment]
@timiyay thanks for suggesting this. Ideally, we'd support merging properties in `turf-union` and `turf-merge`, but we don't right now. At the moment a `union` will give back only the properties of the first polygon

**Comment by morganherlocker** [comment]
I think this should be separate from Turf. Merging properties involves a lot of subjective logic for handling how the properties get merged.  I can think of a dozen equally valid ways to merge a set of properties, which means it's probably not a good idea to set one as a default (ie: aggregate the properties, only use the properties from poly1, concat properties as suggested here, etc.). This logic is something I would typically put in the application layer of an implementation, rather than the library layer, since the preferred behavior is 100% dependent on the algorithm you happen to be writing.

**Comment by timiyay** [comment]
Thanks for all the replies. I'm satisfied that turf.js isn't the place for this, and perhaps a plugin could be made for it.

Happy for this issue to be closed.

I'm currently still deciding whether to do this spatial join on the client, or whether to do everything in PostGIS.

**Comment by morganherlocker** [comment]
> I'm currently still deciding whether to do this spatial join on the client, or whether to do everything in PostGIS.

This is largely a question of how much data you have. Turf can handle huge amounts of data, but a browser typically cannot, while also worrying about UI, bandwidth, and keeping things snappy. Your merge logic does sound a bit complex for a SQL query. For stuff like this I typically use Turf on a node.js server, where it can scale to large datasets. I personally find it much easier to manipulate data in an imperative language like JS, but YMMV.
