### ISSUE TITLE
Feature request: turf.circle

### ISSUE THREAD

**Issue by walling** [Turfjs/turf#301]
This is a proposal to add a function that creates a circle (approximated polygon) given a point and a radius. Example:

```javascript
var point = turf.point([52.521921, 13.399553]);
var circle = turf.circle(point, 50, "km");
```

When the [buffer issue is fixed](https://github.com/Turfjs/turf-buffer/issues/7), the implementation can just be a call to buffer with the point. However, I think this function is useful in itself, and might be easier to implement.

My use case is to be able to specify an area either as a polygon or a circle and using `turf.within` to check my points, instead of having two different code paths (`turf.within` vs. `turf.distance(...) < radius`).

**Some extra thoughts:**

1. The function could take an optional `options`, where you can specify the number of segments and/or a precision. I think the function should have some defaults built-in to provide a good number of segments depending on the radius.

2. If it's too hard to make it work around the north/south poles, I think in the beginning it could be documented as a known issue. At least my own use case is related to major cities around the world.

**Comment by DenisCarriere** [comment]
I agree that this feature would useful since buffer might not be so obvious if you simply want to create a circle.

Since the `turf.buffer` package depends on `jsts` to create the buffer, turf can't really move forward unless there's a solution for an **equidistant buffer** parameter in `jsts`. The radius input always gets converted into Degrees and as we move higher in the latitudes, the measurements of latitudes vs. longitudes are different which skews the polygon to look like an egg shape.

Submitted an issue in `jsts` since this library will fix `turf.buffer`
https://github.com/bjornharrtell/jsts/issues/238

**Comment by benj-d** [comment]
This would be a useful feature and could perhaps be derived from this [existing code](https://github.com/Turfjs/turf-buffer/tree/artisinal ) branch of turf-buffer as [i understand](https://github.com/Turfjs/turf-buffer/issues/7) it can already do geodesic buffering of points and linestrings. 

Unfortunately for me and it seems a few others, i don't know how to convert it from a node.js module to web usable js library but a simplified turf-circle option would be more than enough for a lot of the cases i have seen. An edge resolution option would be a bonus.

This would also be particularly useful for mapbox gl as they advertise and use turf-buffer for generating point buffers (including a sample which is conveniently set to coords 0,0!).

**Comment by jdesboeufs** [comment]
You can look at this: http://terraformer.io/core/#terraformercircle

**Comment by mstdokumaci** [comment]
`turf.circle` is here now: https://github.com/Turfjs/turf/tree/master/packages/turf-circle

**Comment by DenisCarriere** [comment]
Woohoo! Been looking for this update for a long time 👍
