### ISSUE TITLE
Turf.intersect(poly1,poly2) shows offset on the intersection points.

### ISSUE THREAD

**Issue by karanshukla-sarvaha** [Turfjs/turf#348]
Although turf.intersect(poly1,poly2) works good for smaller areas but for larger area polygons it starts showing some offset at the intersection points, the offset grows as the distance grows. This is also seen only for polygons with slanting lines (vertical and horizontal line intersections seem to work well).

I've created a JSFiddle for this : [https://jsfiddle.net/cLe6yo9d/](https://jsfiddle.net/cLe6yo9d/)

The example tries to find the intersection between the black and blue polygons, the intersection is shown as red polygon which is seen shifted from where it should be.

This fiddle has been created by modifying [turf.intersect example](http://turfjs.org/examples/turf-intersect/) to reproduce the issue.

**Comment by tmcw** [comment]
turf-intersect works in wgs84 space, and this example is displayed in mercator. the offset is downwards, as it would be given projection-related skew.

Happy to accept a PR implementing projection support, but closing as invalid since this is a display problem. Straight lines in one projection are not straight in other projections.
