### ISSUE TITLE
Trim unnecessary coordinate precision?

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf#357]
from @mourner 's comment at 

https://github.com/Turfjs/turf-hex-grid/issues/19

---

The current code generates unnecessarily detailed coordinates because there's no rounding:

[-95.59408416187462, 31.27105676807148],
[-95.80518167741707, 31.58431182228841]
We should round to at least 7-8 digits.

---

I'm not sure that this makes sense... why should we limit coordinate precision?

**Comment by mourner** [comment]
Because 7th digit has a maximum margin of error that equals 11mm. We have 14 digits, half of them are simply unnecessary, leading to 2 times bigger sizes of GeoJSON when saved to a file. Although maybe this should be done as a post-processing step with a separate JS module, not as a part of each individual module, most users are unaware of the unnecessary digits.

**Comment by tmcw** [comment]
Yeah, I think this should be in a separate module - the space savings only happens when serializing out geojson, and often turf-using applications don't serialize at all/save to disk, or have lots of temporary results that aren't ever saved.

**Comment by wboykinm** [comment]
I'm hitting file transfer limits when I run my 6-points-of-precision geojson through turf and get 14 points back. Even a separate module for this would be fabulous.

**Comment by mourner** [comment]
@wboykinm just realized that you can probably do without a separate module:

```js
var meta = require('turf.meta');

meta.coordEach(geojson, function (p) {
    p[0] = Math.round(p[0] * 1e6) / 1e6;
    p[1] = Math.round(p[1] * 1e6) / 1e6;
});
```

**Comment by wboykinm** [comment]
SO EASY
