### ISSUE TITLE
squareGrid returns cells outside initial extent

### ISSUE THREAD

**Issue by easherma** [Turfjs/turf#444]
Modified an existing JSFiddle to show this problem:

http://jsfiddle.net/fq7vu2rn/

The documentation for  squareGrid implied that the grid will be created and return cells only inside the extent provided. However, this does not appear to be the way this is handled, as the grid returned does not fall completely within the extent provided.

**Comment by rowanwins** [comment]
Hi @easherma , 

I did some initial work on a [completelyWithin](https://github.com/rowanwins/turf-completelyWithin) module which you could possible use. Basically you'd run your squareGrid calc and the pass the original boundary as well as the resulting grid into completelyWithin.

I think this sort of approach would be preferential rather than introduce another parameter to squareGrid because you'd also then need to add then param to all the other grid types that turf offers.

Having said that my module is just my rough work, it's functional but certainly not part of the turf core.

Hope that helps

**Comment by DenisCarriere** [comment]
👍 This issue exists with all the `grid` modules.

We should add a param `@param {boolean} [completelyWithin=false]` to each grid modules, this would adjust the width & height cellSize spacing to fit exactly within the bbox.

**Currently (without `completelyWithin` param)**
![image](https://cloud.githubusercontent.com/assets/550895/23834426/b29442e6-072c-11e7-928d-e6ff43b4d029.png)

**Comment by DenisCarriere** [comment]
Fixed from PR https://github.com/Turfjs/turf/pull/612.
