### ISSUE TITLE
Question: what does 'cellSize' geometrically measure in the resulting hex_grid

### ISSUE THREAD

**Issue by mikejacktzen** [Turfjs/turf#460]
I've used the hexgrid function and i'm confused at the resulting hexagon properties

https://github.com/Turfjs/turf/tree/master/packages/turf-hex-grid

I can't figure out what the cellSize corresponds to geometrically.

```
cellSize number dimension of cell in specified units
```

'number dimension' is pretty ambiguous

Is it the "long diameter", "short diameter", "side" of a hexagon, or none of the above.

I suspect it's none of the above, since  I've used the turf.area() command for a single hexagon (pulled from the grid of hexagons) and it drastically disagrees with back of the envelope hexagon area calculations using "long/short diameter" and "side

For context, my goal is to get a hexagon grid where each hexagon inscribes a circle of radius 10.

**Comment by morganherlocker** [comment]
cc @jseppi

**Comment by jseppi** [comment]
Hrm, good question. I agree that the description of that argument is ambiguous.

It used to be the "radius" (center to vertex) of a regular hex (in degrees), but that was changed back in https://github.com/turf-junkyard/turf-hex-grid/commit/a2e601ac9c6434bfd415827cc1f3db1738d61721#diff-168726dbe96b3ce427e7fedce31bb0bcR36 (part of this PR https://github.com/turf-junkyard/turf-hex-grid/pull/13). Now it looks like the `cellSize` is a kind of meaningless ratio value :\ Perhaps the hex-grid module should be refactored back to using radius but with the specified units instead of always being degrees.

**Comment by mikejacktzen** [comment]
making the cellSize argument correspond to the radius (in specified units) of the center to the vertex would be perfect.

When I had this question, that was the natural first interpretation that jumped to mind.

It would make my use case (inscribing a hexagon into a circle) automatic.

I'm new to using turf, so for me, it's a good idea. However, i realize maybe the weird hexagon ratio was some systematic choice to align the standards with the other set of grid functions.

**Comment by DenisCarriere** [comment]
@mikejacktzen @jseppi I Agree with both your comments, `cellSize` is a bit vague. Using `diameter` or `radius` would make it easier to understand.

Another thing I noticed is `triangle=true` translates to `radius` for the `cellSize` and `triangle=false` (hexagon) translates to `diameter` for the `cellSize`.

If you measure the diameter of the very bottom left hexagon it's perfectly 50 miles.
https://github.com/Turfjs/turf/blob/master/packages/turf-hex-grid/test/out/grid1.geojson

If you measure the triangle grid (very bottom left triangle) the diameter is 25 miles.
https://github.com/Turfjs/turf/blob/master/packages/turf-hex-grid/test/out/trigrid1.geojson

We could also use the center latitude when applying the `@turf/distance` calculations instead of using the very bottom latitude.

This type of change would be breaking backwards compatibility and would be reserved for the next `major` release of TurfJS.

**Summary**
- [ ] Change `cellSize` param to `radius` or `diameter` (I'm 👍 for diameter).
- [ ] Calculate `xFraction` & `yFraction` from the middle of the `bbox`.
- [ ] Add `completelyWithin` param (ref https://github.com/Turfjs/turf/pull/612)

**Comment by stebogit** [comment]
Just as reference, this was somehow clarified in #623, renaming the parameter to `cellDiameter` and improving the docs with PR #810.
I still think the parameter should be changed, in the next major release, to `cellSide` (equal to the center-to-vertex `radius`), so it's unmistakable and valid also for the triangle output. It will also be consistent with (the recently updated) [`@turf/point-grid`](https://github.com/Turfjs/turf/tree/master/packages/turf-point-grid).

**Comment by DenisCarriere** [comment]
👍 changing parameter to `cellSide` (TurfJS release v5.0+)

**Comment by stebogit** [comment]
`cellSide` renamed in #1019, now the input clearly defines the side of the generated grid (for all grid modules, see #1029)
