### ISSUE TITLE
turfjs.org docs not SSL

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#471]
![image](https://cloud.githubusercontent.com/assets/550895/18358009/21ea186c-75c1-11e6-96d0-adbc12c53285.png)

The SSL certificate is using GitHub's DNS.

![image](https://cloud.githubusercontent.com/assets/550895/18358196/05444b00-75c2-11e6-94d4-80f2a2580f46.png)

Would be nice to see Turf docs as trusted domain.

![image](https://cloud.githubusercontent.com/assets/550895/18358167/d6a5cc2e-75c1-11e6-92a6-6057985631aa.png)

**Comment by tmcw** [comment]
turfjs.org is a github pages site, under a custom domain. We could [get HTTPS if we used turfjs.github.io](https://github.com/blog/2186-https-for-github-pages), but not under the custom domain. Mapbox.com isn't a github pages site, and has a relatively fancy SSL setup.

Closing for now, since this is blocked on GitHub and it's totally unknown if they'll introduce SSL on custom domains soon or never. Happy to accept a contribution that fixes this issue without introducing a lot more complexity.

**Comment by DenisCarriere** [comment]
@tmcw That's a bummer. If I find an easy solution I'll let you know, but for now there's no good solutions.
Thanks for the explanation!

**Comment by DenisCarriere** [comment]
@tmcw Related to this topic, the newly improved GitBooks allows for SSL on custom domains and HTTP2 hosting.

https://www.gitbook.com/blog/features/gitbook-cdn

Might take a while for the transition, however I do know a lot of organizations are moving towards this solution.
