### ISSUE TITLE
Implement Truncate module - drop to 6 decimal precision

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#543]
Just generated some random points/polygons using `turf-random` and the coordinates have 14 digit precision, which is a bit excessive for a completely randomly generated feature.

**Proposal**

Drop to 6 decimals according to the GeoJSON spec RFC 7946 ([Everything you need to know](http://www.macwright.org/2016/11/07/the-geojson-ietf-standard.html) by @tmcw)

```javascript
random('point')
```
```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    70.46923055566859,
                    58.11088890802906
                ]
            },
            "properties": {}
        }
    ]
}
```

**Comment by tmcw** [comment]
I'm open to this idea, though, to be honest, I'm not sure that Turf should have a hand in coordinate precision: Turf is dealing with JavaScript number values, rather than encoded JSON values, and the GeoJSON spec is primarily concerned with the latter. If we start to offer the promise that Turf will always keep coordinates trimmed, there's the very likely case of compounding precision areas if we expand that promise to, say, `turf-concave`, a method that people might run repeatedly.

So... I think there might be a space for this being a separate utility (like `turf.truncate`?) that does decimal truncation only when users explicitly ask for it, thus dodging the potential pitfalls of truncation-by-default?

**Comment by DenisCarriere** [comment]
`turf.truncate` sounds like a good idea. I agree that we shouldn't be be trimming the coordinates by default since this would reduce the speed & performance of Turf.

You would simply need to wrap the `truncate` function to any GeoJSON, easy enough!

```javascript
truncate(random('point'))
//= 6 decimal point
```

**Comment by tmcw** [comment]
Yep, exactly! Here's the [exact spec](https://tools.ietf.org/html/rfc7946#section-11.2) - it doesn't give a great word for what this is, but I'm pretty sure `truncate` is accurate.

**Comment by DenisCarriere** [comment]
@tmcw Sounds good, let me take care of this one, I haven't yet published any new modules for Turf. It might take me sometime get to it, but within the next few weeks I'll send an initial PR.

**Comment by DenisCarriere** [comment]
## New module released 🚀 💥 

Turf `3.9.0` now has `@turf/truncate`, this module truncates the geometry precision for all GeoJSON coordinates, more details can be found within this issue.

FYI: I can confirm that this module is "public" 🤓   

We can close this issue when we've confirmed the latest `@turf/turf` is still working for everyone.

CC: @Turfjs/ownership

**Comment by rowanwins** [comment]
Nice one @DenisCarriere , this will be handy!
