### ISSUE TITLE
Error in turf.concave when passed points are less than 3

### ISSUE THREAD

**Issue by harsh-a1** [Turfjs/turf#550]
Getting the following error when there are less than 3 point features int he array passed to the turf.concave(array,dist,unit) function -
```
Uncaught SyntaxError: Unexpected token u in JSON at position 0(…)
merge @ bundle.js:88087
concave @ bundle.js:88083
(anonymous function)....
```
Looks like bug or am i doing something wrong?

**Comment by DenisCarriere** [comment]
@harsh-a1 Can you provide your input data or post it as a [Gist](https://gist.github.com).

**Comment by harsh-a1** [comment]
Following reproduces it on my machine - 
```
   var pointsX = {
                type:"FeatureCollection",
                features : [ {
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [13,79]
                    }
                }, {
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [13,78]
                    }
                }]
            };

   var hullX = turf.concave(pointsX, 1000, 'kilometers');
```

**Comment by dpmcmlxxvi** [comment]
The underlying issue seems to be the `merge` method used by `concave` which assumes at least 1 feature to merge. There should be a check on `tinPolys` having at least 1 feature.

You can also get the error for more than 2 points if the `maxEdge` parameter filters out too many triangles. Here is a [jsfiddle](https://jsfiddle.net/371r0m8u/4/) that can trigger the error both ways.

**Comment by DenisCarriere** [comment]
Patch merged.
