### ISSUE TITLE
Using Rollup for Turf

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#576]
I am pretty sure everyone would agree on this one, reading back from a few comments from Turf users:

@ThomasG77 

> You may not need to remove JSTS now.
> Why? Because it seems the project is full ES6 compatible and you can use rollup.js to minimized the build  size for buffer in particular.
> You also do not use all JSTS buffer possibilities e.g http://bl.ocks.org/ThomasG77/31037a8897b4980a0818 (illustrated with OpenLayers 3)

@mourner 

> @ThomasG77 oh, nice to see that it switched to ES6 modules! We should consider using rollup.js short term. The main reason to switch is performance though, not bundle size, so we're still pursuing our own implementation of polygon boolean operations.

It's pretty straightforward converting a library to support Rollup, all we really need to do is add `export & import`, the rest of the ES5 code stays the same.

**Rollup Examples**

- Leaflet https://github.com/Leaflet/Leaflet
- Global Mercator (simple rollup config) https://github.com/DenisCarriere/global-mercator

I don't exactly know how we will be tackling this, but I'm willing to help out once we have a plan of attack.

We should set up a new branch `rollup` for this type of work.

**Comment by tmcw** [comment]
Though I've been pretty pro-Rollup on projects that have a single entry point or are used as applications ([iD](https://github.com/openstreetmap/iD), for instance), attempting to use it in Turf-esque projects like [simple-statistics](http://simplestatistics.org/) has been abortive so far. Reason being:

* turf is both a central module and lots of component modules, like turf-extent. We'd need a transpiled build of Turf, as well as transpiled builds of all other modules
* tests will need to use rollup or similar too, and then when tests fail, you'll need to rely on sourcemaps to track down problems
* node.js doesn't support import/export and, so far, is pretty far from being able to, so this overhead will stick around for a while

This is, of course, something of a personal view: for small libraries/modules, I almost exclusively write ES5 or even ES3, because the distribution and testing overhead is so significant, and the lack of native node support.

**Comment by DenisCarriere** [comment]
I can see that single entry point applications would be a lot easier to convert to rollup.

It is very annoying having to build your repo before your tests.

If node.js did support import/export it would be quite different.

@tmcw I'm assuming it's a :-1: for you? I agree 100% with the points you brought up.

I attempted to write a "simple" rollup config for a module and the only way to do it was to include a `rollup.config.js` to each individual turf package and also include a `build` script, this attempt was very painful... :(

**Comment by DenisCarriere** [comment]
We can revisit this topic whenever NodeJS supports `import/export`.

**Comment by DenisCarriere** [comment]
Actually, that day might come sooner then I thought.

Apparently `import/export` is supported in V8 (5.7.458).

https://github.com/nodejs/help/issues/53

NodeJS 7.5 is using V8 (5.4.500.48)

https://nodejs.org/en/download/releases/

I'll re-open this issue and leave room for any more discussion.

**Comment by DenisCarriere** [comment]
Continuing discussion here: https://github.com/Turfjs/turf/issues/583
