### ISSUE TITLE
Rework coordReduce Meta

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#587]
I'm trying to use `@turf/meta` **coordReduce** and it doesn't seem to have the same flow & expected output as [Array.reduce()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce).

**Issues:**
- Missing Index
- Missing Array
- Number of iterations are different (first set of coordinates should be excluded)

**Using Array.reduce()**
```javascript
var line = lineString([[126, -11], [129, -21], [135, -31]]);
var coordinates = line.geometry.coordinates;
coordinates.reduce(function (previous, current, index, array) {
    console.log(previous, current, index, array);
    return current;
});
```

**Output**

```javascript
[ 126, -11 ] [ 129, -21 ] 1 [ [ 126, -11 ], [ 129, -21 ], [ 135, -31 ] ]
[ 129, -21 ] [ 135, -31 ] 2 [ [ 126, -11 ], [ 129, -21 ], [ 135, -31 ] ]
```

**Using Turf Meta coordReduce()**

```javascript
var line = lineString([[126, -11], [129, -21], [135, -31]]);
coordReduce(line, function (previous, current, index, array) {
    console.log(previous, current, index, array);
    return current;
});
```

**Output**
```javascript
undefined [ 126, -11 ] undefined undefined
[ 126, -11 ] [ 129, -21 ] undefined undefined
[ 129, -21 ] [ 135, -31 ] undefined undefined
```
CC: @tmcw

**Comment by tmcw** [comment]
Okay, so some of this is intentional:

> Missing Index

`coordReduce` is designed to work on any data type, including, say, a FeatureCollection of Polygons. We could potentially include a simple auto-incrementing index, but it's not really an equivalent of `reduce`'s index - coordinate `#4` might be the first coordinate in a linestring or the last coordinate of a polygon, for instance.

> Missing Array

This is intentional and we should probably avoid implementing it. coordReduce is iterating over many coordinate arrays in a way intended to allocate as little memory as possible: so it never assembles an array of all the coordinates it'll iterate over.

> Number of iterations are different (first set of coordinates should be excluded)

I learned something new and terrible about JavaScript answering this one:

Array.reduce has [special behavior when you omit the starting value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) which I didn't know about. We could maybe implement this, though we have (correctly) documented the initial value of coordReduce as mandatory, not optional. Providing the starting value causes the two examples to work the same way. I'm not sure if JavaScript's weird behavior is something worth mimicking.

**Comment by DenisCarriere** [comment]
@tmcw Thanks for the quick answer 👍 

> Missing Array

Totally get that! 👍 (wasn't suggesting to add it) working with large geospatial datasets you can quickly run out of memory. This should definitely NOT be included.

> Missing Index

Would be nice to include this, wouldn't be too difficult either, it's pretty handy to have some kind of index to track the order of coordinates. (will need this for `@turf/polygon-slice` & `@turf/line-intersect`)

> Special behavior :)

Kinda shocked me too, the first iteration should be excluded since it `previous` will always be `undefined` and you would never be able to successfully run a reduce operation if you don't have both `previous` & `current`. I understand why it exists on the `Array.map()` method.

@tmcw Do you mind if I send a PR to add `index` & "attempt" to mimic the Array.reduce() iteration.

**Comment by tmcw** [comment]
Yep! `index` and at least trying to implement the special case of Array.reduce sounds good.

**Comment by DenisCarriere** [comment]
@tmcw Quick question, any functional purpose for the `memo` param? It's not existent in the `coordEach`.

**JSDocs Proposed**

**Change**: `callback a method that takes (previous, current, index)`

```javascript
/**
 * @name coordReduce
 * @param {Object} layer any GeoJSON object
 * @param {Function} callback a method that takes (previous, current, index)
 * @param {boolean=} excludeWrapCoord whether or not to include
 * the final coordinate of LinearRings that wraps the ring in its iteration.
 * @returns {*} combined value
```

**JSDocs Before**

**Change**: `callback a method that takes (memo, value) and returns a new memo`

```javascript
/**
 * @name coordReduce
 * @param {Object} layer any GeoJSON object
 * @param {Function} callback a method that takes (memo, value) and returns
 * a new memo
 * @param {*} memo the starting value of memo: can be any type.
 * @param {boolean=} excludeWrapCoord whether or not to include
 * the final coordinate of LinearRings that wraps the ring in its iteration.
 * @returns {*} combined value
```

> Note: We could keep `memo` for Turf 3.X and remove it for the next major release.
> The "backwards" compatible callback would look something like this `(memo, previous, current, index)`

**Comment by tmcw** [comment]
Yes - so memo is short for [memoized](https://en.wikipedia.org/wiki/Memoization), and it's not the 'previous' value in any case but the corner case of the first iteration when called without an initial value. In the normal case where you provide an `initialValue`, the value of memo is the provided initial value in the first call, or the last returned value from the callback in other calls. In that normal case, it isn't equivalent to the previous coordinate, and that's the big difference between reduce and map.

For instance, dumb example of why reduce is useful - calculating the sum of longitudes,

```js
var line = lineString([[126, -11], [129, -21], [135, -31]]);
var sum = coordReduce(line, function (memo, current, index, array) {
    return memo + current[0];
}, 0);
```

On the first iteration memo is 0, then it's 126, then 255, then 390.

This is also why coordReduce has a return value, and coordEach does not - the memo is the eventual return value. Reduce, in this way is part of 'functional programming', since it returns its result, whereas each is more part of imperative, because you just expect it to have side-effects.

**Comment by DenisCarriere** [comment]
👍 Thanks for the answer, ok this really clears up things.

Reading over the `Array.reduce()` and you are correct, `memo` would not be the `previous` instead it would be:

> The accumulated value previously returned in the last invocation of the callback, or initialValue, if supplied.

**Comment by DenisCarriere** [comment]
@tmcw Thanks for the quick feedback, this really helped "re-work" `coordReduce` & `coordEach`.

Closing due to PR fix https://github.com/Turfjs/turf/pull/588.

**Comment by DenisCarriere** [comment]
Here's another definition of the `Array.reduce()` function.

## Microsoft definitions
https://msdn.microsoft.com/en-us/library/ff679975(v=vs.94).aspx

- **previousValue**
> The value from the previous call to the callback function. If an initialValue is provided to the reduce method, the previousValue is initialValue the first time the function is called.
- **currentValue**
>The value of the current array element.
- **currentIndex**
>The numeric index of the current array element.
- **array1**
> The array object that contains the element.

## Mozilla definitions

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

- **accumulator**
> The accumulated value previously returned in the last invocation of the callback, or initialValue, if supplied. (See below.)
- **currentValue**
> The current element being processed in the array.
- **currentIndex**
> The index of the current element being processed in the array. Starts at index 0, if an initialValue is provided, and at index 1 otherwise.
- **array**
> The array reduce was called upon.

**Comment by DenisCarriere** [comment]
@tmcw OK FINALLY.. I've got BOTH examples working. We were both right, you can now use `coordReduce` in both scenarios we mentioned above:

**previous & current coordinates (my example)**

```javascript
var line = lineString([[126, -11], [129, -21], [135, -31]]);
coordReduce(line, function (previousCoords, currentCoords, currentIndex) {
    console.log(previousCoords, currentCoords);
    return currentCoords;
})
```
**output**

```
[ 126, -11 ] [ 129, -21 ] 1
[ 129, -21 ] [ 135, -31 ] 2
```

**memo calculation (your example)**

```javascript
var line = lineString([[126, -11], [129, -21], [135, -31]]);
var sum = coordReduce(line, function (previousValue, currentCoords) {
    console.log('previous:', previousValue);
    var currentValue = previousValue + currentCoords[0];
    return currentValue;
}, 0);
console.log('total:', sum);
```

**output**

```
previous: 0
previous: 126
previous: 255
total: 390
```

### Final JSDocs

```javascript
/**
 * Callback for coordReduce
 *
 * The first time the callback function is called, the values provided as arguments depend
 * on whether the reduce method has an initialValue argument.
 *
 * If an initialValue is provided to the reduce method:
 *  - The previousValue argument is initialValue.
 *  - The currentValue argument is the value of the first element present in the array.
 *
 * If an initialValue is not provided:
 *  - The previousValue argument is the value of the first element present in the array.
 *  - The currentValue argument is the value of the second element present in the array.
 *
 * @private
 * @callback coordReduceCallback
 * @param {*} accumulator The accumulated value previously returned in the last invocation
 * of the callback, or initialValue, if supplied.
 * @param {[number, number]} currentCoords The current coordinate being processed.
 * @param {number} currentIndex The index of the current element being processed in the
 * array.Starts at index 0, if an initialValue is provided, and at index 1 otherwise.
 */

/**
 * Reduce coordinates in any GeoJSON object into a single value,
 * similar to how Array.reduce works. However, in this case we lazily run
 * the reduction, so an array of all coordinates is unnecessary.
 *
 * @name coordReduce
 * @param {Object} layer any GeoJSON object
 * @param {coordReduceCallback} callback a method that takes (previousValue, currentCoords, currentIndex)
 * @param {*} [initialValue] Value to use as the first argument to the first call of the callback.
 * @param {boolean=} excludeWrapCoord whether or not to include
 * the final coordinate of LinearRings that wraps the ring in its iteration.
 * @returns {*} The value that results from the reduction.
 */
function coordReduce(layer, callback, initialValue, excludeWrapCoord) {
```
