### ISSUE TITLE
New Module @turf/mask

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#594]
## New Module `@turf/mask` 🎉 

> Takes a Polygon and an optional mask and returns the outside area.

Released on [npm](https://www.npmjs.com/package/@turf/mask) as a minor release `TurfJS 3.12`.

### Supported Geometry types

- FeatureCollection & Feature
- Polygon & MultiPolygon

### To-Do

- [ ] ~Mask outside of Polygon extent~
- [x] Overlapping FeatureCollection Polygons

### Visuals

**Input**

![image](https://cloud.githubusercontent.com/assets/550895/23584707/60723900-0137-11e7-828d-841396ec2d43.png)

**Output**

![image](https://cloud.githubusercontent.com/assets/550895/23584708/6f18e49a-0137-11e7-8caa-ca874cadc36b.png)

### JSDocs

```javascript
/**
 * Takes any type of {@link Polygon|polygon} and an optional mask and returns a {@link Polygon|polygon} exterior ring with holes.
 *
 * @name mask
 * @param {FeatureCollection|Feature<Polygon|MultiPolygon>} polygon GeoJSON Polygon used as interior rings or holes.
 * @param {Feature<Polygon>} [mask] GeoJSON Polygon used as the exterior ring (if undefined, the world extent is used)
 * @return {Feature<Polygon>} Masked Polygon (exterior ring with holes).
 * @example
 * var poylgon = {
 *     "type": "Feature",
 *     "properties": {},
 *     "geometry": {
 *       "type": "Polygon",
 *       "coordinates": [
 *         [[100, 0], [101, 0], [101,1], [100,1], [100, 0]]
 *      ]
 *    }
 * }
 * var masked = turf.mask(polygon);
 * //=masked
 */
module.exports = function (polygon, mask) {
```

### Benchmark

Very fast for basic operations!

```
$ node bench.js
basic x 1,449,519 ops/sec ±0.66% (93 runs sampled)
feature-collection x 914,708 ops/sec ±1.18% (90 runs sampled)
multipolygon x 869,793 ops/sec ±0.90% (85 runs sampled)
```

### Contributors

@tmcw, @rowanwins & @deniscarriere

CC: @Turfjs/ownership 
Closing issues: #493

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Can you clarify the first task that is outstanding, is this where the input polygon falls outside the extent of the input polygon like [your previous example](https://github.com/Turfjs/turf/pull/589#issuecomment-283650775)?

**Comment by DenisCarriere** [comment]
@rowanwins I've added the outstanding results to [`test/out`](https://github.com/Turfjs/turf/tree/master/packages/turf-mask/test/out).

Since we've got the "basic" mask operations, we should create a new `mask` branch in Turf to include the "advance" mask operations, many of these advance operations will require `@turf/polygon-slice` and/or `@turf/union`.

- [mask-outside](https://github.com/Turfjs/turf/blob/master/packages/turf-mask/test/out/mask-outside/results.geojson)
![image](https://cloud.githubusercontent.com/assets/550895/23592875/6d4fe3c2-01d5-11e7-95bc-ead5f65b1225.png)

- [overlapping](https://github.com/Turfjs/turf/blob/master/packages/turf-mask/test/out/overlapping/results.geojson)

![image](https://cloud.githubusercontent.com/assets/550895/23592898/aa6ddb92-01d5-11e7-8935-6e9b8f999f16.png)

**Comment by rowanwins** [comment]
hmmm these additional scenarios are kinda tricky, in my opinion they are quite left field and aren't the expected use case for a mask operation so I'd kinda be reluctant to expand the code base to cater for them.... 

Perhaps we should to get a third opinion - perhaps @andrewharvey would like to weigh in given that it was his idea (and he's Australian and I've met him :) )

**Comment by DenisCarriere** [comment]
Just because they are tricky, doesn't mean they aren't valid inputs. It shouldn't be that hard to implement it, turf should have all the tools internally to do such operations.

**Comment by andrewharvey** [comment]
Hey @rowanwins thanks for implementing this!

I honestly didn't think about these corner cases when I originally requested the mask feature. Since I only had the single polygon against a full globe mask use case in mind.

That said, if you passed for example a MultiPolygon with overlapping areas I would expect a mask operation to treat overlapping regions just the same as non-overlapping regions and cut them out. How this is implemented weather by ruining a dissolve, or calculating the parity of the overlapping sections to cut it out, I'm not sure.

For the mask outside case, I would expect the area outside to be unfilled. So not what I'm seeing in the above screenshot.

It would be nice if these corner cases were accommodated for, but it's not my call if they are necessary to ship this feature.

**Comment by andrewharvey** [comment]
@DenisCarriere Correct. Although this is more like a difference operation. The use case I had in mind was a workaround for https://github.com/mapbox/mapbox-gl-js/issues/993 so if you had a small area of interest, like an airport, could could create a global mask layer so that the rest of the world was dimmed out leaving only that airport in focus.

**Comment by rowanwins** [comment]
Im with @andrewharvey that the mask outside case that it is more like a difference operation. I tend to err on the side that the user should be forced to make some good decisions about which operation they are using rather than covering all these uses cases (which in this case I'd argue is not a genuine mask). We could perhaps do an extent check at the start of the operation and if the input falls outside the extent of the mask then we could throw an error?

For the overlapping polygons yeah I think we could probably do some dissolve if a collection of polys is passed in.

**Comment by DenisCarriere** [comment]
The initial steps would check if the bounding box of the features are inside the mask, if it's not... 1. cause an error, or 2. apply difference operations.

- The difference operations will only run if the bbox of the features are outside the extent.
- The dissolve operation will only run if polygon inputs collide with each other.

Rbush will be used to detect those collisions.

The parameters of this `mask` method aren't too wild, input can be any type of polygons and the mask can ONLY be a simple polygon. We've already eliminated some of the VERY strange input/output combinations.

As long as you user inputs the valid GeoJSON for the params, then the TurfJS module should handle it.

**Comment by caopeng000** [comment]
Is there a java sdk api?turf.mask(polygon); thanks

**Comment by rowanwins** [comment]
Hi @caopeng000 

Turf is a javascript based project, a number of attempts have been made to port Turf to other languages such as Swift. But I haven't heard of anything java based.

**Comment by caopeng000** [comment]
https://github.com/mapbox/mapbox-java/blob/master/mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfJoins.java

**Comment by caopeng000** [comment]
turf other api have, but mask this method is missing

**Comment by rowanwins** [comment]
Hi @caopeng000 

The project you reference is maintained by Mapbox, you'll need to open an issue in that repo.

**Comment by caopeng000** [comment]
ok,thanks
