### ISSUE TITLE
distance between two hexagons in hexgrid

### ISSUE THREAD

**Issue by agaase** [Turfjs/turf#623]
I am trying to find distance between two hexagons in a hex grid and as far as my understand goes, it should be equal to the cell size we pass while creating the hexgrid.
`hexGrid = turf.hexGrid(bbox, 1,"kilometers")`

but when I try to find the distance between centroid of two cells using `distance` api, the value I get is less than the cell size. I am using the below code.
`turf.centroid(tile)`
`turf.distance(from, to,"kilometers")`

The cell size is 1kilometers and what get back as distance is 0.866 kilometers.

Please help!

**Comment by morganherlocker** [comment]
@agaase  The cell size is only approximate, since hex grids are designed to look uniform on a web mercator map. The distance function, however, calculates a geodesic distance that approximates the spherical shape of the earth. The amount of spherical distortion seen in your hex grid will vary depending on the size and location of the grid. If you need precisely equal cells, I would recommend writing your own geodesic hex grid implementation (this could be done using `@turf/turf-destination`).

**Comment by stebogit** [comment]
I believe the `@turf/hex-grid` documentation needs some clarification.
When reading the [article](http://www.redblobgames.com/grids/hexagons/) provided in [the docs](http://turfjs.org/docs/#hexgrid), the `size` (which I'd assume corresponds to the `cellSize` parameter of `hex-grid`) represents the radius of the circumcircle of the hexagon, thus the side of the hexagon.
However the current output of `@turf/hex-grid` uses `cellSize` as the diameter of said circle, i.e. twice the side of the hexagon.

@agaase assuming `cellSize` is equal to the hexagon width (diameter of its circumcircle, `D`), I'd say the distance between centroids `d` is actually correct.
In fact:
[`d = Math.sqrt(3) * D`](https://en.wikipedia.org/wiki/Hexagon#Parameters)
which means `cellSize` = 1 km  =>  `distance` = 0.866 km

![screen shot 2017-06-19 at 9 37 43 pm](https://user-images.githubusercontent.com/12717225/27323775-a392da54-5557-11e7-8f3d-94faa803020a.png)

cc: @DenisCarriere

**Comment by DenisCarriere** [comment]
👍 Thanks @stebogit, we could simply change the `cellSize` param to `diameter`, would that make more sense for the docs?

**Comment by stebogit** [comment]
@DenisCarriere that would probably be more clear, maybe even `cellDiameter`.
However since there are actually two circles you can refer to (inscribed and circumscribed), a simple `cellSide` would be probably best. Besides, it would make sense also for triangular grid, as it would represent the side of the triangles as well.

![screen shot 2017-06-20 at 8 28 18 am](https://user-images.githubusercontent.com/12717225/27341659-bddcb00c-5592-11e7-99a3-9bf25e43ce68.png)

**Comment by DenisCarriere** [comment]
Awesome, `cellSide` or `cellDiameter` are good names for parameters. Next time anyone touches those `grid` modules we can update the params.

**Comment by stebogit** [comment]
@DenisCarriere renaming the parameter to `cellSide` would imply changing its meaning, i.e. a breaking change, and thus correcting all the tests... 😳 
I'll just rename it `cellDiameter`, improve the documentation and add a test to prove the distance between centroids.

**Comment by BrendanJM** [comment]
> d = Math.sqrt(3) * D

I know this was closed forever ago, but a minor correction here for anyone who stumbles across this looking for ways to calculate the distance between hexagon centroids. This should read d = `Math.sqrt(3) * D / 2`, if D is defined as the full diameter of the hex (as it appears in the picture). Alternatively if D is defined as the length of a single edge, the above holds.
