### ISSUE TITLE
ArcByCenterPoint

### ISSUE THREAD

**Issue by Adraesh** [Turfjs/turf#649]
Hi!

I did not find any method provided by the Turf lib which handle my case.

In fact, I have:

- startAngle (degrees)
- endAngle (degrees)
- radius (kilometers)
- centerPoint (long, lat) Center of the whole circle.

Basically I want to generate and ArcByCenterPoint with those data.

Is it possible ?

Thanks.

**Comment by Adraesh** [comment]
Hi!

I just tested the turf-sector method and obviously there is a misunderstanding. Well the mode itself is working perfectly but this is not what I asked.

<img width="611" alt="screen shot 2017-04-09 at 6 07 22 pm" src="https://cloud.githubusercontent.com/assets/3873988/24838411/035c5504-1d50-11e7-8cb3-2bf5e9e6c18e.png">

In fact I got a circle sector but what I want is ONLY the line Arc not the entire sector :)

Thanks!

**Comment by DenisCarriere** [comment]
I don't think there's any misunderstanding, what @stebogit implemented lines up perfectly with https://github.com/Turfjs/turf/issues/155.

This new module request would be called `@turf/line-arc` which would have this as a result (red line):

![image](https://cloud.githubusercontent.com/assets/550895/24838702/44ffa716-1d1b-11e7-8322-69b2402dcbbd.png)

@Adraesh Feel free to send a PR to TurfJS if you want specific modules implemented.

**Comment by Adraesh** [comment]
Thanks Denis, but what I wanted to say is that my post can't be referenced to the turf-sector module newly implemented :)

**Comment by stebogit** [comment]
@DenisCarriere @Adraesh I can easily implement a `turf-arc-line` module simply extracting a currently private function inside the `sector` module.

**Comment by Adraesh** [comment]
Hey stebogit!

I believe you are talking about this method: 

function getArcLine(center, radius, angle1, angle2, steps, units)

I would be really appreciated if you can do that.

Thank you very much.

**Comment by DenisCarriere** [comment]
👍 @stebogit Sounds like a plan, afterwards you can add `@turf/line-arc` as a dependency to `@turf/sector`.

**Comment by DenisCarriere** [comment]
Thanks to @stebogit [`@turf/line-arc`](https://www.npmjs.com/package/@turf/line-arc) is now available on npm.

**Comment by stebogit** [comment]
Tanks also @DenisCarriere! 👍 
I'll add `@turf/line-arc` as a dependency to `@turf/sector` then.

**Comment by aziz-boudi4** [comment]
I'm using a `<Layer>` and a `<Feature> from `react-mapbox-gl` to draw a line from `Point A` to `Point B` ( see screenshot 1)

My goal is to use `line-arc` and `center` from `turf js` in order to have a curved line between `point A` and `point B` 

I managed to get a curved line, but it's not starting at `Point A` and it's not finishing at `Point B`... it is instead drawn in the middle of the map (see screenshot number 2) 

Here is my code 
`
    const features = turf.featureCollection([
      turf.point(this.state.startFlying),   // [-122.3811441, 37.6213129]
      turf.point(this.state.destinationFlying),  // [-118.4107187, 33.9415889]
    ]);

    const theCenter = turf.center(features);
    const arcRadius = 5;
    const bearing1 = 25;
    const bearing2 = 47;

    const arc = turf.lineArc(theCenter, arcRadius, bearing1, bearing2);
    const mappedCurvedFlyingCurve = arc.geometry.coordinates;
`

![screen shot 2018-01-08 at 1 17 16 pm](https://user-images.githubusercontent.com/7435015/34693196-9d5d4b32-f477-11e7-91f5-500173bf234f.png)

![screen shot 2018-01-08 at 1 22 10 pm](https://user-images.githubusercontent.com/7435015/34693204-a3a3f202-f477-11e7-9c9d-95588ed2b403.png)

![screen shot 2018-01-08 at 1 22 31 pm](https://user-images.githubusercontent.com/7435015/34693213-a953b890-f477-11e7-8144-8d6112582d98.png)
