### ISSUE TITLE
flatten: Geometry Collection in Feature Collection does not flatten

### ISSUE THREAD

**Issue by dpmcmlxxvi** [Turfjs/turf#709]
While working on a PR for #692 to create a `flattenEach` method I noticed that `@turf/flatten` does not appear to flatten a geometry collection that is inside a feature collection. See the [jsfiddle](https://jsfiddle.net/hofaehwk/).

Not sure if this is the intended behavior. The GeoJSON [spec](https://tools.ietf.org/html/rfc7946) discourages nesting geometry collections but I see nothing about nesting a geometry collection in a feature collection. So, seems like a valid use case.

I was planning on having the PR for #692 iterate over the same features that are yielded using `@turf/flatten` so I'd like some clarification on what is the desired behavior. If the current implementation is a bug than I can use a proper flattening in the PR.

The fix for the current implementation seems simple enough. Have an additional check for a `GeometryCollection` type in the switch case of `flattenFeatureCollection`.

```javascript
case 'MultiPoint':
case 'MultiLineString':
case 'MultiPolygon':
case 'GeometryCollection':
    featureEach(flatten(multiFeature), function (feature) {
        features.push(feature);
    });
break;
```

- [X] GeoJSON data as a [gist file](https://gist.github.com/) or [geojson.io](http://geojson.io/) (filename extension must be `.geojson`).
- [X] Snippet of source code or for complex examples use [jsfiddle](https://jsfiddle.net/).

**Comment by DenisCarriere** [comment]
Never knew that GeometryCollection inside a FeatureCollection was a thing (seems like it is), you are correct by saying nested GeometryCollection shouldn't be allowed.

You might have issues using [`featureEach`](https://github.com/Turfjs/turf/tree/master/packages/turf-meta#featureeach) on a Geometry Collection since that will only return Features, you will need to use [`geomEach`](https://github.com/Turfjs/turf/tree/master/packages/turf-meta#geomeach) if you want to iterate over the Geometry Collection.

**Question:** Should the output remain a FeatureCollection regardless of the input geometry (open to suggestions)?

| Input | Output |
|:------|:-------|
| `Feature<Point>` | `FeatureCollection<Point>` |
| `Feature<MultiPoint>` | `FeatureCollection<Point>` |
| `FeatureCollection<MultiPoint>` | `FeatureCollection<Point>` |
| `Geometry<Point>` | `FeatureCollection<Point>` |
| `Geometry<MultiPoint>` | `FeatureCollection<Point>` |
| `GeometryCollection<Point>` | `FeatureCollection<Point>` |

**Comment by DenisCarriere** [comment]
@dpmcmlxxvi I'm starting to get the same frustrations you're having using the `@turf/flatten` module. There's definitely a place for having `flattenEach` & `flattenReduce` in `@turf/meta`. 👍

**Comment by dpmcmlxxvi** [comment]
Agreed. I think having a `FeatureCollection<Point|LineString|Polygon>` as output regardless of input would be the most expected result. At least to me that's what the word `flatten` most suggests - reducing everything to a single geometries.

**Comment by DenisCarriere** [comment]
👍 Another thing I noticed with flatten is when you provide a Geometry Object it returns a FeatureCollection with Geometries (not Features).

Let me know if you want to tackle adding `flattenEach` & `flattenReduce` to [`@turf/meta`](https://github.com/Turfjs/turf/blob/master/packages/turf-meta/index.js) or do you want me to take of it? Most of the logic is already done, just need to piece it together into `turf-meta`.

**Comment by dpmcmlxxvi** [comment]
@DenisCarriere Yeah, I'll be submitting the PR pretty soon. Agree on it hopefully simplifying the flatten code. All the crucial logic is already being done in `geomEach`.

**Comment by dpmcmlxxvi** [comment]
Flattening GeometryCollection in FeatureCollection is now supported in `@turf/meta/flattenEach` `@turf/flatten` with updates #712 and #724. In fact, it should now support any valid GeoJSON.
