### ISSUE TITLE
Handling negative buffer with NaN coordinates

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#745]
Based on https://github.com/Turfjs/turf/pull/736#issuecomment-301937747, I wanted to add this **morphological closing** behavior to the test cases, however I noticed when entering a `radius` which is greater than the polygon, the geometry's coordinates will result in `NaN` values.

**Question:** Is this expected output correct? Or should we return `undefined` or an empty `FeatureCollection`?

### Example

https://jsfiddle.net/pvLx12n1/
```javascript
const poly = turf.polygon([[[11, 0], [22, 4], [31, 0], [31, 11], [21, 15], [11, 11], [11, 0]]]);
turf.buffer(poly, -500, 'miles').geometry.coordinates;
//=[ [ NaN, NaN ] ]
```

### Output Geometry

> Seems like this output would be an invalid GeoJSON Polygon

```json
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [[null, null]]
  }
}
```

CC: @rafaelalmeida

**Comment by rafaelalmeida** [comment]
I would be in favor of returning `undefined`. See the map of the polygon you made:

http://geojson.io/#id=gist:anonymous/7d16198bde157fea2b8783f2fd29dfcb&map=4/12.77/16.00

The vertical line is about 800 miles long (check by clicking it and going to the "Info" tab). With a -500 miles buffer, the middle part of the polygon will shrink 500 miles from each side, meaning they would "overlap" - shrunk bottom would go above shrunk top, basically "folding the polygon inside out".

Theoretically, we could arbitrarily _define_ the negative buffer operation such that the Polygon would "go around" if the negative buffer is large enough. However, I think it would not be a good idea, because:

1. Not sure if the underlying JSTS algorithm would support that, or even the practicality of making such an algorithm from scratch;
2. The results could be very confusing - given a large enough magnitude, your negative buffer would yield a polygon larger than the one you started with

That being said, since it's not clear how this would behave, and we did not _define_ the behavior, `undefined` would be the semantically correct way to represent this (unless there's other JS-wide or project-wide conventions around the semantics of `undefined` which would override this).

**Comment by DenisCarriere** [comment]
👍 Thanks for the feedback @rafaelalmeida, I agree we return `undefined` if GeoJSON has no geometry. If the input is a FeatureCollection and none of the outputs have geometries then an empty FeatureCollection should be returned.

**Comment by rafaelalmeida** [comment]
Agree with the empty `FeatureCollection` behavior as well. What if only some polygons are undefined? Do we silently return only the viable ones?

**Comment by DenisCarriere** [comment]
Yes, if a feature collection of 2 polygons is the input and only 1 of them has valid geometry, then the FeatureCollection will only contain 1 polygon.

Returning a "bad" geometry would most likely cause things to break by having `NaN` in the coordinates.

**Comment by rafaelalmeida** [comment]
Agreed. If there's an easy mechanism to return error details along with
response, maybe it could be used if the cost to implement is low enough.
Otherwise, a quick note in the docs would suffice, like:

"When using a negative radius, the resulting geometry may be invalid if
it's too small compared to the radius magnitude. If the input is a
FeatureCollection, only valid members will be returned in the output
FeatureCollection - i.e., the output collection may have fewer members than
the input, or even be empty."

While this does not say exactly what failed, should give devs a hint on
where to look.
