### ISSUE TITLE
@turf/lineSplit doesn't handle antimeridian correctly

### ISSUE THREAD

**Issue by gabrielflorit** [Turfjs/turf#782]
Hello,

It seems `lineSplit` doesn't like it when lines cross the antimeridian. Here's a simple example: https://jsfiddle.net/3fa5c6st/1/ 

```js
var splitter = turf.lineString([
  [0, 0],
  [0, 10]
])

var line = turf.lineString([
  [179, 0],
  [-179, 0]
])

var result = turf.lineSplit(line, splitter) // => returns splits
```

There should be no splits - `line` and `splitter` are on opposite sides of the globe. But `lineString` returns splits - incorrect ones.

Is this user error? If not, how can I help?

**Comment by DenisCarriere** [comment]
This is most likely a bug, a lot of Turf modules have difficulty when going over the antimeridian.

**Comment by stebogit** [comment]
@gabrielflorit I'd actually say the output is technically correct, since a `line` that goes from -179˚ to 179˚ does pass through the 0˚ meridian, so it should be splitted in half by your `splitter`.

Based on what I quite recently learned from @tmcw's [article](https://macwright.org/2016/09/26/the-180th-meridian.html) about "the 180th meridian issue", your `line` input should probably be something like
```js
var line = turf.lineString([
  [-181, 0],
  [-179, 0]
])
```
which does not cross the 0 meridian.
With this input `@turf/lineSplit` will output an empty `FeatureCollection`, as expected.

@DenisCarriere do you agree?

**Comment by DenisCarriere** [comment]
We won't be able to do much on TurfJS to solve this issue, dealing with GeoJSON going over the anti-meridian I would follow @tmcw's recommendations / [article](https://macwright.org/2016/09/26/the-180th-meridian.html) about "the 180th meridian issue".

This anti-meridian geometry handling would best be handled on the client side and not handle by TurfJS.

I'm going to suggest we don't attempt to solve this issue in TurfJS.

**Comment by erikh2000** [comment]
If you wanted the caller to take responsibility for passing coords that don't rely on wrapping from 180 to -180, it might make sense for Turf to provide functions for fixing the coords prior to them being passed in a Turf call.

**Comment by gabrielflorit** [comment]
^ that would be ideal. Otherwise how will users know when not to use Turf?

**Comment by stebogit** [comment]
How would you unmistakably determine if the user means `[-179, 0], [179, 0]` or actually `[-179, 0],[-181, 0]`?
Both are (in web-mercator) 100% valid, but they represent different lines.
I believe Turf could and should prevent wrong computed output, but it can/should not "interpret" user's input. The 180th meridian issue is due to the web-mercator projection/system itself that the user needs to consider when using Turf.

**Comment by erikh2000** [comment]
@stebogit, I am picturing a function where the user translates anti-meridian-wrapped coords to unwrapped and can be specific about how the coordinate translation is made (e.g. handling either of the two options you described). The idea is to make the user aware of the translation and think it through instead of it being automatic. So maybe an unwrapPoints(Feature, TranslationMethod) function along a complementary wrapPoints(Feature) that puts all points in bounds of the coordinate system. The second function could be used on features returned from other Turf functions that relied on receiving unwrapped points to perform their calcs.

**Comment by DenisCarriere** [comment]
Going to close this issue since this is a limitation of Web-Mercator/GeoJSON Spec, we won't be able to solve this antimeridian issue.
