### ISSUE TITLE
Isoline from example returning MultiLineString with no coordinates

### ISSUE THREAD

**Issue by bakerac4** [Turfjs/turf#829]
Following the example found at http://turfjs.org/docs/#isolines after downloading the minified turf.js file and including it in my project ends up giving me 10 features that each have 1 geometry object inside, with type MultiLineString that has an empty array of coordinates. 

Here is a GIST of the GeoJSON I am getting back
https://gist.github.com/bakerac4/89656a65e7388b290d223facdaf5dc75

The code I am using seems to be a copy and paste from the docs.
```javascript
var points = turf.random('point', 100, {
  bbox: [0, 30, 20, 50]
});
for (var i = 0; i < points.features.length; i++) {
  points.features[i].properties.temperature = Math.random() * 10;
}
var breaks = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
var isolines = turf.isolines(points, breaks, 'temperature');
```

**Comment by DenisCarriere** [comment]
Huh... interesting.

Also getting the same result:

```javascript
//= isoloines.features[0]
{ type: 'Feature',
  properties: { temperature: 1 },
  geometry: { type: 'MultiLineString', coordinates: [] } }
```

Thoughts? @stebogit

**Comment by stebogit** [comment]
@bakerac4 `turf-isolines` (like [`turf-isobands`](http://turfjs.org/docs/#isobands)) expects a [`pointGrid`](http://turfjs.org/docs/#pointgrid) as input, which will be internally converter into a matrix (`Array<Array<number>>`) of `zProperty` values to be able to calculate the isolines. With just random points there is no matrix (that's why a [`@turf/interpolate`](https://github.com/Turfjs/turf/issues/24) module has been desirable for long time).
If you have though a matrix and you want to convert it into a `pointGrid` you could use [matrix-to-grid](https://github.com/stebogit/matrix-to-grid#readme).

I'm surprised (and sorry) the documentation have not been correctly updated when the module was re-implemented, I'll commit the appropriate correction.

**Comment by stebogit** [comment]
Done. I did also fix a small bug in `isobands` and made sure also its example was working.
@DenisCarriere how can I update also the website?

**Comment by bakerac4** [comment]
Thank you @stebogit for clearing that up. That leaves me a bit confused about something (and Im sure its just me misunderstanding something). Does `pointGrid` create a grid of points that are always evenly spaced out?  

Im trying to create a isoline heatmap like [this](http://bic.iwlearn.org/en/atlas/atlas/86-2-atmospheric-air-condition-irkutsk_the-isolines) but I am being given a list of objects (with lat, lng and temp). From what Im gathering, since @turf/interpolate doesn't actually exist yet Im out of luck? 

Thanks again for your help !

**Comment by stebogit** [comment]
> Does pointGrid create a grid of points that are always evenly spaced out?

Yes @bakerac4, this is an example of [`pointGrid`](http://turfjs.org/docs/#pointgrid) output
![screen shot 2017-07-07 at 7 37 06 am](https://user-images.githubusercontent.com/12717225/27962567-296fb560-62e7-11e7-8c32-d22f9fef1d78.png)

> I'm trying to create a isoline heatmap like this 

You might want to take a look at `@turf/isobands` then, it's probably what you need as it created the contour polygons instead of just the isolines.

>  I'm out of luck?

Look at [`@turf/idw`](http://turfjs.org/docs/#idw), it might give you some hints on how to generate a `pointGrid`.

**Comment by DenisCarriere** [comment]
👍 @bakerac4 interpolation operations with TurfJS can be significantly improved, like @stebogit was mentioning, you might have a better result using one of these TurfJS libraries:

- [`@turf/idw`](http://turfjs.org/docs/#idw)
- [`@turf/isobands`](http://turfjs.org/docs/#isobands)

**Comment by Ir001** [comment]
![Screenshot 2023-11-06 114847](https://github.com/Turfjs/turf/assets/31561620/e9715ab4-4d08-4206-92fe-ba0cb0ebc179)
Im using isobands for creating contour. If i using `Math.random()` for zProperty value its work
![Screenshot 2023-11-06 114725](https://github.com/Turfjs/turf/assets/31561620/a022dc05-8f50-45c4-934b-0122e448fa3e)

![Screenshot 2023-11-06 115157](https://github.com/Turfjs/turf/assets/31561620/f8533d98-b933-48f4-8676-8239ae023270)
,but if i use real data isoband returning MultiPolygon with empty coordinates.
