### ISSUE TITLE
Can the slice branch be merged and the function put on npm?

### ISSUE THREAD

**Issue by alexgleith** [Turfjs/turf#880]
I need to use the polygon slice function, and note that the branch is drifting behind and the function is not published on npm.

Is there any reason why it's not merged, because if there is, I can potentially do some work to fix it?

**Comment by stebogit** [comment]
@alexgleith the branch has not been merged because still under development. It seems it's not trivial at all. Please take a look at the comments of the PR #580 so you can have an idea of the status.
You are more than welcome to [contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md)! 😄

**Comment by rowanwins** [comment]
Always good to express interest in a module @alexgleith , then we know someone actually wants to use it :)

**Comment by alexgleith** [comment]
I really want to use it!

I'm hacking on the `slice` branch for a quick-fix. The current state exports lines, so I'm going to get it polygonising properly first.

Am I right in understanding that the failing test is the issue? It's a bit unclear what's missing otherwise...

**Comment by DenisCarriere** [comment]
The proposed `slice` module will be pushed after `v5.0` is released.

**Comment by rowanwins** [comment]
Going to close this in favour of #580 which contains more info
