### ISSUE TITLE
package.json in turf module defines dependencies with caret operator

### ISSUE THREAD

**Issue by grundid** [Turfjs/turf#891]
The @turf/* dependencies in the turf module are defined with the ^ operator.
This means it is not possible to install an older version of @ turf/turf because all submodules are installed up to version 4.9.9.

For example, using
`npm install @turf/turf@4.5.2 --save --save-exact`
still installs the 4.6.x version of all modules.

**Comment by DenisCarriere** [comment]
Agreed, we're using `Lerna` for publishing new releases.

https://github.com/lerna/lerna

Maybe there's a special way to publish that I'm unaware.

**Comment by grundid** [comment]
I'm not familiar with Lerna, but by looking at the docs the --exact parameter looks similar to the npm install --save-exact parameter.

`lerna publish --exact`

Maybe you can try the next release with this parameter?

**Comment by DenisCarriere** [comment]
👍 Will do

**Comment by mfedderly** [comment]
A lot has changed since 2017 when it comes to repeatable builds in the JS ecosystem. I'd argue that these days you want the caret versions to be there (dependency deduplicating) and you'd use package-lock.json or yarn.lock to fix the versions to the ones you want. If you disagree please reopen this ticket and lets have a discussion about it.
