### ISSUE TITLE
Intersect documentation is outdated

### ISSUE THREAD

**Issue by ricardo-kagawa** [Turfjs/turf#951]
The documentation at http://turfjs.org/docs/#intersect says that `intersect` returns `undefined` for empty intersections, but it seems that it now returns an empty `Feature` instead, since `4.7.1`.

I guess that should have been a major version update, since that is a breaking change. It breaks what is explicitly documented (so `intersect(a, b) === undefined` does not work anymore), and related idioms (like `intersect(a, b) || c`).

**Comment by DenisCarriere** [comment]
Agreed, I don't remember the exact reason why this was changed (strangely it was me who made that change https://github.com/Turfjs/turf/commit/fd592c0473e68c490e77056f08783b5419ab1e48).

I personally prefer this type of idiom `intersects(a, b) || c`.

Additionally, the output was change from `undefined` to `null` from @stebogit (edit https://github.com/Turfjs/turf/commit/ea9551d2bbe746f01754335998238b8b6dc27bb8)

🤔 ... I would have no issues reverting this change back to `undefined` (or `null`) instead of returning an empty Feature.

@stebogit your thoughts?

**Comment by DenisCarriere** [comment]
This change should also reflect [@turf/difference](https://github.com/Turfjs/turf/tree/master/packages/turf-difference)

**Comment by stebogit** [comment]
@DenisCarriere @ricardo-kagawa I am not a big fan of `Feature<null>` either. Also, I would say in this case it's more appropriate returning `null` (which in my understanding means "none") instead of `undefined` (like "undetermined).
Good job @DenisCarriere!

> This change should also reflect `@turf/difference`

We should definitely update `@turf/difference` as well 👍

**Comment by DenisCarriere** [comment]
Both libraries have been published to reflect `null` returns.
