### ISSUE TITLE
turf.intersect returns polygon with null geometry instead of undefined

### ISSUE THREAD

**Issue by colllin** [Turfjs/turf#961]
The docs say that `turf.intersect` will return `undefined` in the case where the geometries do not intersect.  I'm currently seeing (v4.7.3) that it returns a polygon with `geometry: null` when the geometries do not intersect.

Update: To be clear, the bug I'm seeing is that it returns a Polygon object with `geometry: null`, and previously we were expecting it to return just `undefined` rather than any kind of Polygon object.

**Comment by colllin** [comment]
Looks like this may already be fixed?  https://github.com/Turfjs/turf/commit/df481ca280576672277678523a44e71dd2948c21#diff-4db71116796d555a0638cd247cafeffe

**Comment by DenisCarriere** [comment]
👍 Thanks for reporting this, yes this has been fixed in https://github.com/Turfjs/turf/pull/952

The change from `undefined` to `null` is because `undefined` would define it as missing, `null` indicates that you did apply the `intersect` method but it returned an empty result, making the difference between both is useful.

I'll update a patch release for this instead of waiting for the next official release.

**Comment by DenisCarriere** [comment]
Published a new patch release for `@turf/intersect` & `@turf/difference` at `v4.7.4`.

**Comment by colllin** [comment]
Thanks Denis! Fast work. Just to be sure — did you see my note about returning a Polygon object vs. the previous behavior of returning undefined directly? This was a breaking change for our code which expected to receive a falsey value from `intersect()`, but now receives a Polygon with a falsey geometry.
